-- ==================== PUBLIC SCHEMA BACKUP ====================
-- File: C:/Users/marka/.config/superpowers/worktrees/qyzen/rename-modules-to-assessments/database/backups/2026-06-12-pre-module-to-assessment-public-schema.sql
-- Created: 2026-06-12
-- Purpose: Live schema backup for public before module-to-assessment migration.
CREATE SCHEMA IF NOT EXISTS "public";


-- ==================== SEQUENCES ====================

CREATE SEQUENCE IF NOT EXISTS "public"."academic_term_new_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."academic_year_new_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."permissions_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."role_permissions_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."roles_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."tbl_enrolled_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."tbl_group_chat_messages_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."tbl_group_chat_reads_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."tbl_group_chats_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."tbl_learning_materials_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."tbl_modules_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."tbl_notifications_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."tbl_quizzes_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."tbl_scores_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."tbl_sections_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."tbl_sections_term_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."tbl_student_module_retakes_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."tbl_student_presence_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."tbl_subjects_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."tbl_user_roles_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."tbl_users_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;


-- ==================== TABLES ====================

CREATE TABLE IF NOT EXISTS "public"."tbl_academic_term" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "term_name" text NOT NULL,
  "semester" text NOT NULL,
  "academic_year_id" bigint NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_academic_year" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "year" text NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_enrolled" (
  "id" bigint DEFAULT nextval('tbl_enrolled_id_seq'::regclass) NOT NULL,
  "student_id" bigint NOT NULL,
  "educator_id" bigint NOT NULL,
  "subject_id" bigint NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_group_chat_messages" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "group_chat_id" bigint NOT NULL,
  "sender_user_id" bigint NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_group_chat_reads" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "group_chat_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "last_read_at" timestamp with time zone NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_group_chats" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "educator_id" bigint NOT NULL,
  "subject_id" bigint NOT NULL,
  "section_id" bigint NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_learning_materials" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "educator_id" bigint NOT NULL,
  "subject_id" bigint NOT NULL,
  "section_id" bigint NOT NULL,
  "storage_bucket" text DEFAULT 'learning-materials'::text NOT NULL,
  "storage_path" text NOT NULL,
  "file_name" text NOT NULL,
  "file_extension" text NOT NULL,
  "mime_type" text NOT NULL,
  "file_size" bigint DEFAULT 0 NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_modules" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "educator_id" bigint NOT NULL,
  "subject_id" bigint NOT NULL,
  "section_id" bigint NOT NULL,
  "module_code" text NOT NULL,
  "time_limit" text NOT NULL,
  "cheating_attempts" integer DEFAULT 0 NOT NULL,
  "is_shuffle" boolean DEFAULT false NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "start_time" time without time zone NOT NULL,
  "end_time" time without time zone NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "term" bigint NOT NULL,
  "allow_review" boolean DEFAULT false NOT NULL,
  "allow_hint" boolean DEFAULT false NOT NULL,
  "hint_count" integer DEFAULT 0 NOT NULL,
  "allow_retake" boolean DEFAULT false NOT NULL,
  "retake_count" integer DEFAULT 0 NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_notifications" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "recipient_user_id" bigint NOT NULL,
  "actor_user_id" bigint NOT NULL,
  "event_type" text NOT NULL,
  "title" text NOT NULL,
  "message" text NOT NULL,
  "link_path" text,
  "module_id" bigint,
  "subject_id" bigint,
  "section_id" bigint,
  "metadata" jsonb,
  "is_read" boolean DEFAULT false NOT NULL,
  "read_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_permissions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text NOT NULL,
  "resource" text NOT NULL,
  "action" text NOT NULL,
  "description" text NOT NULL,
  "module" text NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "permission_string" text GENERATED ALWAYS AS (((resource || ':'::text) || action)) STORED
);
CREATE TABLE IF NOT EXISTS "public"."tbl_quizzes" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "module_id" bigint NOT NULL,
  "subject_id" bigint NOT NULL,
  "section_id" bigint NOT NULL,
  "educator_id" bigint NOT NULL,
  "question" text NOT NULL,
  "quiz_type" text NOT NULL,
  "choices" jsonb,
  "correct_answer" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_role_permissions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "role_id" bigint NOT NULL,
  "permission_id" bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_roles" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text NOT NULL,
  "description" text NOT NULL,
  "is_system" boolean DEFAULT false NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_scores" (
  "id" bigint DEFAULT nextval('tbl_scores_id_seq'::regclass) NOT NULL,
  "student_id" bigint NOT NULL,
  "educator_id" bigint NOT NULL,
  "module_id" bigint NOT NULL,
  "subject_id" bigint NOT NULL,
  "section_id" bigint NOT NULL,
  "score" integer,
  "total_questions" integer DEFAULT 0 NOT NULL,
  "student_answer" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "warning_attempts" integer DEFAULT 0 NOT NULL,
  "status" text DEFAULT 'in_progress'::text NOT NULL,
  "is_passed" boolean DEFAULT false NOT NULL,
  "taken_at" timestamp with time zone DEFAULT now() NOT NULL,
  "submitted_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_sections" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "educator_id" bigint NOT NULL,
  "academic_term_id" bigint NOT NULL,
  "section_name" text NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_sections_term" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "section_id" bigint NOT NULL,
  "academic_term_id" bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_student_module_retakes" (
  "id" bigint DEFAULT nextval('tbl_student_module_retakes_id_seq'::regclass) NOT NULL,
  "educator_id" bigint NOT NULL,
  "student_id" bigint NOT NULL,
  "module_id" bigint NOT NULL,
  "extra_retake_count" integer DEFAULT 0 NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_student_presence" (
  "id" bigint DEFAULT nextval('tbl_student_presence_id_seq'::regclass) NOT NULL,
  "student_id" bigint NOT NULL,
  "last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
  "current_path" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_subjects" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "educator_id" bigint NOT NULL,
  "sections_id" bigint NOT NULL,
  "subject_code" text NOT NULL,
  "subject_name" text NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."tbl_user_roles" (
  "id" bigint DEFAULT nextval('tbl_user_roles_id_seq'::regclass) NOT NULL,
  "user_id" bigint NOT NULL,
  "role_id" bigint NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at" timestamp with time zone
);
CREATE TABLE IF NOT EXISTS "public"."tbl_users" (
  "id" bigint DEFAULT nextval('tbl_users_id_seq'::regclass) NOT NULL,
  "user_type" text NOT NULL,
  "user_id" text NOT NULL,
  "given_name" text NOT NULL,
  "surname" text NOT NULL,
  "email" text NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at" timestamp with time zone,
  "profile_picture" text,
  "cover_photo" text
);


-- ==================== CONSTRAINTS ====================

ALTER TABLE ONLY "public"."tbl_academic_term" DROP CONSTRAINT IF EXISTS "academic_term_new_semester_check";
ALTER TABLE ONLY "public"."tbl_academic_term" ADD CONSTRAINT "academic_term_new_semester_check" CHECK ((semester = ANY (ARRAY['1st Semester'::text, '2nd Semester'::text])));
ALTER TABLE ONLY "public"."tbl_academic_term" DROP CONSTRAINT IF EXISTS "academic_term_new_academic_year_id_fkey";
ALTER TABLE ONLY "public"."tbl_academic_term" ADD CONSTRAINT "academic_term_new_academic_year_id_fkey" FOREIGN KEY (academic_year_id) REFERENCES tbl_academic_year(id) ON DELETE RESTRICT;
ALTER TABLE ONLY "public"."tbl_academic_term" DROP CONSTRAINT IF EXISTS "academic_term_new_pkey";
ALTER TABLE ONLY "public"."tbl_academic_term" ADD CONSTRAINT "academic_term_new_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_academic_term" DROP CONSTRAINT IF EXISTS "academic_term_new_unique_term";
ALTER TABLE ONLY "public"."tbl_academic_term" ADD CONSTRAINT "academic_term_new_unique_term" UNIQUE (term_name, semester, academic_year_id);
ALTER TABLE ONLY "public"."tbl_academic_year" DROP CONSTRAINT IF EXISTS "academic_year_new_pkey";
ALTER TABLE ONLY "public"."tbl_academic_year" ADD CONSTRAINT "academic_year_new_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_academic_year" DROP CONSTRAINT IF EXISTS "academic_year_new_year_key";
ALTER TABLE ONLY "public"."tbl_academic_year" ADD CONSTRAINT "academic_year_new_year_key" UNIQUE (year);
ALTER TABLE ONLY "public"."tbl_enrolled" DROP CONSTRAINT IF EXISTS "tbl_enrolled_educator_id_fkey";
ALTER TABLE ONLY "public"."tbl_enrolled" ADD CONSTRAINT "tbl_enrolled_educator_id_fkey" FOREIGN KEY (educator_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_enrolled" DROP CONSTRAINT IF EXISTS "tbl_enrolled_student_id_fkey";
ALTER TABLE ONLY "public"."tbl_enrolled" ADD CONSTRAINT "tbl_enrolled_student_id_fkey" FOREIGN KEY (student_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_enrolled" DROP CONSTRAINT IF EXISTS "tbl_enrolled_subject_id_fkey";
ALTER TABLE ONLY "public"."tbl_enrolled" ADD CONSTRAINT "tbl_enrolled_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES tbl_subjects(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_enrolled" DROP CONSTRAINT IF EXISTS "tbl_enrolled_pkey";
ALTER TABLE ONLY "public"."tbl_enrolled" ADD CONSTRAINT "tbl_enrolled_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_group_chat_messages" DROP CONSTRAINT IF EXISTS "tbl_group_chat_messages_content_check";
ALTER TABLE ONLY "public"."tbl_group_chat_messages" ADD CONSTRAINT "tbl_group_chat_messages_content_check" CHECK ((char_length(btrim(content)) > 0));
ALTER TABLE ONLY "public"."tbl_group_chat_messages" DROP CONSTRAINT IF EXISTS "tbl_group_chat_messages_group_chat_id_fkey";
ALTER TABLE ONLY "public"."tbl_group_chat_messages" ADD CONSTRAINT "tbl_group_chat_messages_group_chat_id_fkey" FOREIGN KEY (group_chat_id) REFERENCES tbl_group_chats(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_group_chat_messages" DROP CONSTRAINT IF EXISTS "tbl_group_chat_messages_sender_user_id_fkey";
ALTER TABLE ONLY "public"."tbl_group_chat_messages" ADD CONSTRAINT "tbl_group_chat_messages_sender_user_id_fkey" FOREIGN KEY (sender_user_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_group_chat_messages" DROP CONSTRAINT IF EXISTS "tbl_group_chat_messages_pkey";
ALTER TABLE ONLY "public"."tbl_group_chat_messages" ADD CONSTRAINT "tbl_group_chat_messages_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_group_chat_reads" DROP CONSTRAINT IF EXISTS "tbl_group_chat_reads_group_chat_id_fkey";
ALTER TABLE ONLY "public"."tbl_group_chat_reads" ADD CONSTRAINT "tbl_group_chat_reads_group_chat_id_fkey" FOREIGN KEY (group_chat_id) REFERENCES tbl_group_chats(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_group_chat_reads" DROP CONSTRAINT IF EXISTS "tbl_group_chat_reads_user_id_fkey";
ALTER TABLE ONLY "public"."tbl_group_chat_reads" ADD CONSTRAINT "tbl_group_chat_reads_user_id_fkey" FOREIGN KEY (user_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_group_chat_reads" DROP CONSTRAINT IF EXISTS "tbl_group_chat_reads_pkey";
ALTER TABLE ONLY "public"."tbl_group_chat_reads" ADD CONSTRAINT "tbl_group_chat_reads_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_group_chat_reads" DROP CONSTRAINT IF EXISTS "tbl_group_chat_reads_unique_pair";
ALTER TABLE ONLY "public"."tbl_group_chat_reads" ADD CONSTRAINT "tbl_group_chat_reads_unique_pair" UNIQUE (group_chat_id, user_id);
ALTER TABLE ONLY "public"."tbl_group_chats" DROP CONSTRAINT IF EXISTS "tbl_group_chats_educator_id_fkey";
ALTER TABLE ONLY "public"."tbl_group_chats" ADD CONSTRAINT "tbl_group_chats_educator_id_fkey" FOREIGN KEY (educator_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_group_chats" DROP CONSTRAINT IF EXISTS "tbl_group_chats_section_id_fkey";
ALTER TABLE ONLY "public"."tbl_group_chats" ADD CONSTRAINT "tbl_group_chats_section_id_fkey" FOREIGN KEY (section_id) REFERENCES tbl_sections(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_group_chats" DROP CONSTRAINT IF EXISTS "tbl_group_chats_subject_id_fkey";
ALTER TABLE ONLY "public"."tbl_group_chats" ADD CONSTRAINT "tbl_group_chats_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES tbl_subjects(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_group_chats" DROP CONSTRAINT IF EXISTS "tbl_group_chats_pkey";
ALTER TABLE ONLY "public"."tbl_group_chats" ADD CONSTRAINT "tbl_group_chats_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_group_chats" DROP CONSTRAINT IF EXISTS "tbl_group_chats_unique_classroom";
ALTER TABLE ONLY "public"."tbl_group_chats" ADD CONSTRAINT "tbl_group_chats_unique_classroom" UNIQUE (educator_id, subject_id, section_id);
ALTER TABLE ONLY "public"."tbl_learning_materials" DROP CONSTRAINT IF EXISTS "tbl_learning_materials_educator_id_fkey";
ALTER TABLE ONLY "public"."tbl_learning_materials" ADD CONSTRAINT "tbl_learning_materials_educator_id_fkey" FOREIGN KEY (educator_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_learning_materials" DROP CONSTRAINT IF EXISTS "tbl_learning_materials_section_id_fkey";
ALTER TABLE ONLY "public"."tbl_learning_materials" ADD CONSTRAINT "tbl_learning_materials_section_id_fkey" FOREIGN KEY (section_id) REFERENCES tbl_sections(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_learning_materials" DROP CONSTRAINT IF EXISTS "tbl_learning_materials_subject_id_fkey";
ALTER TABLE ONLY "public"."tbl_learning_materials" ADD CONSTRAINT "tbl_learning_materials_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES tbl_subjects(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_learning_materials" DROP CONSTRAINT IF EXISTS "tbl_learning_materials_pkey";
ALTER TABLE ONLY "public"."tbl_learning_materials" ADD CONSTRAINT "tbl_learning_materials_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_modules" DROP CONSTRAINT IF EXISTS "tbl_modules_educator_id_fkey";
ALTER TABLE ONLY "public"."tbl_modules" ADD CONSTRAINT "tbl_modules_educator_id_fkey" FOREIGN KEY (educator_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_modules" DROP CONSTRAINT IF EXISTS "tbl_modules_section_id_fkey";
ALTER TABLE ONLY "public"."tbl_modules" ADD CONSTRAINT "tbl_modules_section_id_fkey" FOREIGN KEY (section_id) REFERENCES tbl_sections(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_modules" DROP CONSTRAINT IF EXISTS "tbl_modules_subject_id_fkey";
ALTER TABLE ONLY "public"."tbl_modules" ADD CONSTRAINT "tbl_modules_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES tbl_subjects(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_modules" DROP CONSTRAINT IF EXISTS "tbl_modules_term_fkey";
ALTER TABLE ONLY "public"."tbl_modules" ADD CONSTRAINT "tbl_modules_term_fkey" FOREIGN KEY (term) REFERENCES tbl_academic_term(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_modules" DROP CONSTRAINT IF EXISTS "tbl_modules_pkey";
ALTER TABLE ONLY "public"."tbl_modules" ADD CONSTRAINT "tbl_modules_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_modules" DROP CONSTRAINT IF EXISTS "tbl_modules_unique_code_per_subject_section_term";
ALTER TABLE ONLY "public"."tbl_modules" ADD CONSTRAINT "tbl_modules_unique_code_per_subject_section_term" UNIQUE (module_code, subject_id, section_id, term);
ALTER TABLE ONLY "public"."tbl_notifications" DROP CONSTRAINT IF EXISTS "tbl_notifications_event_type_check";
ALTER TABLE ONLY "public"."tbl_notifications" ADD CONSTRAINT "tbl_notifications_event_type_check" CHECK ((event_type = ANY (ARRAY['module_created'::text, 'module_updated'::text, 'module_deleted'::text, 'learning_material_uploaded'::text, 'learning_material_deleted'::text, 'quiz_created'::text, 'quiz_uploaded'::text, 'quiz_updated'::text, 'quiz_deleted'::text, 'enrollment_created'::text, 'enrollment_updated'::text, 'enrollment_deleted'::text, 'retake_updated'::text, 'quiz_submitted'::text])));
ALTER TABLE ONLY "public"."tbl_notifications" DROP CONSTRAINT IF EXISTS "tbl_notifications_actor_user_id_fkey";
ALTER TABLE ONLY "public"."tbl_notifications" ADD CONSTRAINT "tbl_notifications_actor_user_id_fkey" FOREIGN KEY (actor_user_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_notifications" DROP CONSTRAINT IF EXISTS "tbl_notifications_module_id_fkey";
ALTER TABLE ONLY "public"."tbl_notifications" ADD CONSTRAINT "tbl_notifications_module_id_fkey" FOREIGN KEY (module_id) REFERENCES tbl_modules(id) ON DELETE SET NULL;
ALTER TABLE ONLY "public"."tbl_notifications" DROP CONSTRAINT IF EXISTS "tbl_notifications_recipient_user_id_fkey";
ALTER TABLE ONLY "public"."tbl_notifications" ADD CONSTRAINT "tbl_notifications_recipient_user_id_fkey" FOREIGN KEY (recipient_user_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_notifications" DROP CONSTRAINT IF EXISTS "tbl_notifications_section_id_fkey";
ALTER TABLE ONLY "public"."tbl_notifications" ADD CONSTRAINT "tbl_notifications_section_id_fkey" FOREIGN KEY (section_id) REFERENCES tbl_sections(id) ON DELETE SET NULL;
ALTER TABLE ONLY "public"."tbl_notifications" DROP CONSTRAINT IF EXISTS "tbl_notifications_subject_id_fkey";
ALTER TABLE ONLY "public"."tbl_notifications" ADD CONSTRAINT "tbl_notifications_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES tbl_subjects(id) ON DELETE SET NULL;
ALTER TABLE ONLY "public"."tbl_notifications" DROP CONSTRAINT IF EXISTS "tbl_notifications_pkey";
ALTER TABLE ONLY "public"."tbl_notifications" ADD CONSTRAINT "tbl_notifications_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_permissions" DROP CONSTRAINT IF EXISTS "permissions_pkey";
ALTER TABLE ONLY "public"."tbl_permissions" ADD CONSTRAINT "permissions_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_permissions" DROP CONSTRAINT IF EXISTS "permissions_permission_string_key";
ALTER TABLE ONLY "public"."tbl_permissions" ADD CONSTRAINT "permissions_permission_string_key" UNIQUE (permission_string);
ALTER TABLE ONLY "public"."tbl_quizzes" DROP CONSTRAINT IF EXISTS "tbl_quizzes_quiz_type_check";
ALTER TABLE ONLY "public"."tbl_quizzes" ADD CONSTRAINT "tbl_quizzes_quiz_type_check" CHECK ((quiz_type = ANY (ARRAY['multiple_choice'::text, 'identification'::text])));
ALTER TABLE ONLY "public"."tbl_quizzes" DROP CONSTRAINT IF EXISTS "tbl_quizzes_educator_id_fkey";
ALTER TABLE ONLY "public"."tbl_quizzes" ADD CONSTRAINT "tbl_quizzes_educator_id_fkey" FOREIGN KEY (educator_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_quizzes" DROP CONSTRAINT IF EXISTS "tbl_quizzes_module_id_fkey";
ALTER TABLE ONLY "public"."tbl_quizzes" ADD CONSTRAINT "tbl_quizzes_module_id_fkey" FOREIGN KEY (module_id) REFERENCES tbl_modules(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_quizzes" DROP CONSTRAINT IF EXISTS "tbl_quizzes_section_id_fkey";
ALTER TABLE ONLY "public"."tbl_quizzes" ADD CONSTRAINT "tbl_quizzes_section_id_fkey" FOREIGN KEY (section_id) REFERENCES tbl_sections(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_quizzes" DROP CONSTRAINT IF EXISTS "tbl_quizzes_subject_id_fkey";
ALTER TABLE ONLY "public"."tbl_quizzes" ADD CONSTRAINT "tbl_quizzes_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES tbl_subjects(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_quizzes" DROP CONSTRAINT IF EXISTS "tbl_quizzes_pkey";
ALTER TABLE ONLY "public"."tbl_quizzes" ADD CONSTRAINT "tbl_quizzes_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_role_permissions" DROP CONSTRAINT IF EXISTS "role_permissions_permission_id_fkey";
ALTER TABLE ONLY "public"."tbl_role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY (permission_id) REFERENCES tbl_permissions(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_role_permissions" DROP CONSTRAINT IF EXISTS "role_permissions_role_id_fkey";
ALTER TABLE ONLY "public"."tbl_role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY (role_id) REFERENCES tbl_roles(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_role_permissions" DROP CONSTRAINT IF EXISTS "role_permissions_pkey";
ALTER TABLE ONLY "public"."tbl_role_permissions" ADD CONSTRAINT "role_permissions_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_role_permissions" DROP CONSTRAINT IF EXISTS "role_permissions_unique_pair";
ALTER TABLE ONLY "public"."tbl_role_permissions" ADD CONSTRAINT "role_permissions_unique_pair" UNIQUE (role_id, permission_id);
ALTER TABLE ONLY "public"."tbl_roles" DROP CONSTRAINT IF EXISTS "roles_name_check";
ALTER TABLE ONLY "public"."tbl_roles" ADD CONSTRAINT "roles_name_check" CHECK ((name ~ '^[a-z]+(_[a-z]+)*$'::text));
ALTER TABLE ONLY "public"."tbl_roles" DROP CONSTRAINT IF EXISTS "roles_pkey";
ALTER TABLE ONLY "public"."tbl_roles" ADD CONSTRAINT "roles_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_roles" DROP CONSTRAINT IF EXISTS "roles_name_key";
ALTER TABLE ONLY "public"."tbl_roles" ADD CONSTRAINT "roles_name_key" UNIQUE (name);
ALTER TABLE ONLY "public"."tbl_scores" DROP CONSTRAINT IF EXISTS "tbl_scores_status_check";
ALTER TABLE ONLY "public"."tbl_scores" ADD CONSTRAINT "tbl_scores_status_check" CHECK ((status = ANY (ARRAY['in_progress'::text, 'submitted'::text, 'passed'::text, 'failed'::text])));
ALTER TABLE ONLY "public"."tbl_scores" DROP CONSTRAINT IF EXISTS "tbl_scores_educator_id_fkey";
ALTER TABLE ONLY "public"."tbl_scores" ADD CONSTRAINT "tbl_scores_educator_id_fkey" FOREIGN KEY (educator_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_scores" DROP CONSTRAINT IF EXISTS "tbl_scores_module_id_fkey";
ALTER TABLE ONLY "public"."tbl_scores" ADD CONSTRAINT "tbl_scores_module_id_fkey" FOREIGN KEY (module_id) REFERENCES tbl_modules(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_scores" DROP CONSTRAINT IF EXISTS "tbl_scores_section_id_fkey";
ALTER TABLE ONLY "public"."tbl_scores" ADD CONSTRAINT "tbl_scores_section_id_fkey" FOREIGN KEY (section_id) REFERENCES tbl_sections(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_scores" DROP CONSTRAINT IF EXISTS "tbl_scores_student_id_fkey";
ALTER TABLE ONLY "public"."tbl_scores" ADD CONSTRAINT "tbl_scores_student_id_fkey" FOREIGN KEY (student_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_scores" DROP CONSTRAINT IF EXISTS "tbl_scores_subject_id_fkey";
ALTER TABLE ONLY "public"."tbl_scores" ADD CONSTRAINT "tbl_scores_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES tbl_subjects(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_scores" DROP CONSTRAINT IF EXISTS "tbl_scores_pkey";
ALTER TABLE ONLY "public"."tbl_scores" ADD CONSTRAINT "tbl_scores_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_sections" DROP CONSTRAINT IF EXISTS "tbl_sections_academic_term_id_fkey";
ALTER TABLE ONLY "public"."tbl_sections" ADD CONSTRAINT "tbl_sections_academic_term_id_fkey" FOREIGN KEY (academic_term_id) REFERENCES tbl_academic_term(id) ON DELETE RESTRICT;
ALTER TABLE ONLY "public"."tbl_sections" DROP CONSTRAINT IF EXISTS "tbl_sections_educator_id_fkey";
ALTER TABLE ONLY "public"."tbl_sections" ADD CONSTRAINT "tbl_sections_educator_id_fkey" FOREIGN KEY (educator_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_sections" DROP CONSTRAINT IF EXISTS "tbl_sections_pkey";
ALTER TABLE ONLY "public"."tbl_sections" ADD CONSTRAINT "tbl_sections_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_sections_term" DROP CONSTRAINT IF EXISTS "tbl_sections_term_academic_term_id_fkey";
ALTER TABLE ONLY "public"."tbl_sections_term" ADD CONSTRAINT "tbl_sections_term_academic_term_id_fkey" FOREIGN KEY (academic_term_id) REFERENCES tbl_academic_term(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_sections_term" DROP CONSTRAINT IF EXISTS "tbl_sections_term_section_id_fkey";
ALTER TABLE ONLY "public"."tbl_sections_term" ADD CONSTRAINT "tbl_sections_term_section_id_fkey" FOREIGN KEY (section_id) REFERENCES tbl_sections(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_sections_term" DROP CONSTRAINT IF EXISTS "tbl_sections_term_pkey";
ALTER TABLE ONLY "public"."tbl_sections_term" ADD CONSTRAINT "tbl_sections_term_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_sections_term" DROP CONSTRAINT IF EXISTS "tbl_sections_term_unique_pair";
ALTER TABLE ONLY "public"."tbl_sections_term" ADD CONSTRAINT "tbl_sections_term_unique_pair" UNIQUE (section_id, academic_term_id);
ALTER TABLE ONLY "public"."tbl_student_module_retakes" DROP CONSTRAINT IF EXISTS "tbl_student_module_retakes_educator_id_fkey";
ALTER TABLE ONLY "public"."tbl_student_module_retakes" ADD CONSTRAINT "tbl_student_module_retakes_educator_id_fkey" FOREIGN KEY (educator_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_student_module_retakes" DROP CONSTRAINT IF EXISTS "tbl_student_module_retakes_module_id_fkey";
ALTER TABLE ONLY "public"."tbl_student_module_retakes" ADD CONSTRAINT "tbl_student_module_retakes_module_id_fkey" FOREIGN KEY (module_id) REFERENCES tbl_modules(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_student_module_retakes" DROP CONSTRAINT IF EXISTS "tbl_student_module_retakes_student_id_fkey";
ALTER TABLE ONLY "public"."tbl_student_module_retakes" ADD CONSTRAINT "tbl_student_module_retakes_student_id_fkey" FOREIGN KEY (student_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_student_module_retakes" DROP CONSTRAINT IF EXISTS "tbl_student_module_retakes_pkey";
ALTER TABLE ONLY "public"."tbl_student_module_retakes" ADD CONSTRAINT "tbl_student_module_retakes_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_student_presence" DROP CONSTRAINT IF EXISTS "tbl_student_presence_student_id_fkey";
ALTER TABLE ONLY "public"."tbl_student_presence" ADD CONSTRAINT "tbl_student_presence_student_id_fkey" FOREIGN KEY (student_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_student_presence" DROP CONSTRAINT IF EXISTS "tbl_student_presence_pkey";
ALTER TABLE ONLY "public"."tbl_student_presence" ADD CONSTRAINT "tbl_student_presence_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_subjects" DROP CONSTRAINT IF EXISTS "tbl_subjects_educator_id_fkey";
ALTER TABLE ONLY "public"."tbl_subjects" ADD CONSTRAINT "tbl_subjects_educator_id_fkey" FOREIGN KEY (educator_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_subjects" DROP CONSTRAINT IF EXISTS "tbl_subjects_sections_id_fkey";
ALTER TABLE ONLY "public"."tbl_subjects" ADD CONSTRAINT "tbl_subjects_sections_id_fkey" FOREIGN KEY (sections_id) REFERENCES tbl_sections(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_subjects" DROP CONSTRAINT IF EXISTS "tbl_subjects_pkey";
ALTER TABLE ONLY "public"."tbl_subjects" ADD CONSTRAINT "tbl_subjects_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_subjects" DROP CONSTRAINT IF EXISTS "tbl_subjects_unique_code_per_section";
ALTER TABLE ONLY "public"."tbl_subjects" ADD CONSTRAINT "tbl_subjects_unique_code_per_section" UNIQUE (educator_id, sections_id, subject_code);
ALTER TABLE ONLY "public"."tbl_subjects" DROP CONSTRAINT IF EXISTS "tbl_subjects_unique_name_per_section";
ALTER TABLE ONLY "public"."tbl_subjects" ADD CONSTRAINT "tbl_subjects_unique_name_per_section" UNIQUE (educator_id, sections_id, subject_name);
ALTER TABLE ONLY "public"."tbl_user_roles" DROP CONSTRAINT IF EXISTS "user_roles_role_id_fkey";
ALTER TABLE ONLY "public"."tbl_user_roles" ADD CONSTRAINT "user_roles_role_id_fkey" FOREIGN KEY (role_id) REFERENCES tbl_roles(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_user_roles" DROP CONSTRAINT IF EXISTS "user_roles_user_id_fkey";
ALTER TABLE ONLY "public"."tbl_user_roles" ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES tbl_users(id) ON DELETE CASCADE;
ALTER TABLE ONLY "public"."tbl_user_roles" DROP CONSTRAINT IF EXISTS "user_roles_pkey";
ALTER TABLE ONLY "public"."tbl_user_roles" ADD CONSTRAINT "user_roles_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_user_roles" DROP CONSTRAINT IF EXISTS "user_roles_user_role_unique";
ALTER TABLE ONLY "public"."tbl_user_roles" ADD CONSTRAINT "user_roles_user_role_unique" UNIQUE (user_id, role_id);
ALTER TABLE ONLY "public"."tbl_users" DROP CONSTRAINT IF EXISTS "users_user_type_check";
ALTER TABLE ONLY "public"."tbl_users" ADD CONSTRAINT "users_user_type_check" CHECK ((user_type = ANY (ARRAY['admin'::text, 'student'::text, 'educator'::text])));
ALTER TABLE ONLY "public"."tbl_users" DROP CONSTRAINT IF EXISTS "users_pkey";
ALTER TABLE ONLY "public"."tbl_users" ADD CONSTRAINT "users_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."tbl_users" DROP CONSTRAINT IF EXISTS "users_email_key";
ALTER TABLE ONLY "public"."tbl_users" ADD CONSTRAINT "users_email_key" UNIQUE (email);
ALTER TABLE ONLY "public"."tbl_users" DROP CONSTRAINT IF EXISTS "users_user_id_key";
ALTER TABLE ONLY "public"."tbl_users" ADD CONSTRAINT "users_user_id_key" UNIQUE (user_id);


-- ==================== INDEXES ====================

CREATE UNIQUE INDEX IF NOT EXISTS academic_term_new_pkey ON public.tbl_academic_term USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS academic_term_new_unique_term ON public.tbl_academic_term USING btree (term_name, semester, academic_year_id);
CREATE UNIQUE INDEX IF NOT EXISTS academic_year_new_pkey ON public.tbl_academic_year USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS academic_year_new_year_key ON public.tbl_academic_year USING btree (year);
CREATE INDEX IF NOT EXISTS idx_tbl_enrolled_educator_id ON public.tbl_enrolled USING btree (educator_id);
CREATE INDEX IF NOT EXISTS idx_tbl_enrolled_student_id ON public.tbl_enrolled USING btree (student_id);
CREATE INDEX IF NOT EXISTS idx_tbl_enrolled_subject_id ON public.tbl_enrolled USING btree (subject_id);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_enrolled_pkey ON public.tbl_enrolled USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_enrolled_unique_student_subject_per_educator ON public.tbl_enrolled USING btree (educator_id, student_id, subject_id);
CREATE INDEX IF NOT EXISTS idx_tbl_group_chat_messages_group_chat_created_at ON public.tbl_group_chat_messages USING btree (group_chat_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tbl_group_chat_messages_sender_user_id ON public.tbl_group_chat_messages USING btree (sender_user_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_group_chat_messages_pkey ON public.tbl_group_chat_messages USING btree (id);
CREATE INDEX IF NOT EXISTS idx_tbl_group_chat_reads_group_chat_last_read_at ON public.tbl_group_chat_reads USING btree (group_chat_id, last_read_at DESC);
CREATE INDEX IF NOT EXISTS idx_tbl_group_chat_reads_user_id ON public.tbl_group_chat_reads USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_group_chat_reads_pkey ON public.tbl_group_chat_reads USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_group_chat_reads_unique_pair ON public.tbl_group_chat_reads USING btree (group_chat_id, user_id);
CREATE INDEX IF NOT EXISTS idx_tbl_group_chats_educator_id ON public.tbl_group_chats USING btree (educator_id);
CREATE INDEX IF NOT EXISTS idx_tbl_group_chats_section_id ON public.tbl_group_chats USING btree (section_id);
CREATE INDEX IF NOT EXISTS idx_tbl_group_chats_subject_id ON public.tbl_group_chats USING btree (subject_id);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_group_chats_pkey ON public.tbl_group_chats USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_group_chats_unique_classroom ON public.tbl_group_chats USING btree (educator_id, subject_id, section_id);
CREATE INDEX IF NOT EXISTS idx_tbl_learning_materials_educator_id ON public.tbl_learning_materials USING btree (educator_id);
CREATE INDEX IF NOT EXISTS idx_tbl_learning_materials_section_id ON public.tbl_learning_materials USING btree (section_id);
CREATE INDEX IF NOT EXISTS idx_tbl_learning_materials_storage_path ON public.tbl_learning_materials USING btree (storage_bucket, storage_path);
CREATE INDEX IF NOT EXISTS idx_tbl_learning_materials_subject_id ON public.tbl_learning_materials USING btree (subject_id);
CREATE INDEX IF NOT EXISTS idx_tbl_learning_materials_updated_at ON public.tbl_learning_materials USING btree (updated_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_learning_materials_pkey ON public.tbl_learning_materials USING btree (id);
CREATE INDEX IF NOT EXISTS idx_tbl_modules_educator_id ON public.tbl_modules USING btree (educator_id);
CREATE INDEX IF NOT EXISTS idx_tbl_modules_module_code ON public.tbl_modules USING btree (module_code);
CREATE INDEX IF NOT EXISTS idx_tbl_modules_section_id ON public.tbl_modules USING btree (section_id);
CREATE INDEX IF NOT EXISTS idx_tbl_modules_start_date ON public.tbl_modules USING btree (start_date);
CREATE INDEX IF NOT EXISTS idx_tbl_modules_subject_id ON public.tbl_modules USING btree (subject_id);
CREATE INDEX IF NOT EXISTS idx_tbl_modules_term ON public.tbl_modules USING btree (term);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_modules_pkey ON public.tbl_modules USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_modules_unique_code_per_subject_section_term ON public.tbl_modules USING btree (module_code, subject_id, section_id, term);
CREATE INDEX IF NOT EXISTS idx_tbl_notifications_actor_user_id ON public.tbl_notifications USING btree (actor_user_id);
CREATE INDEX IF NOT EXISTS idx_tbl_notifications_module_id ON public.tbl_notifications USING btree (module_id);
CREATE INDEX IF NOT EXISTS idx_tbl_notifications_recipient_created_at ON public.tbl_notifications USING btree (recipient_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tbl_notifications_recipient_unread_created_at ON public.tbl_notifications USING btree (recipient_user_id, is_read, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_notifications_pkey ON public.tbl_notifications USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS permissions_permission_string_key ON public.tbl_permissions USING btree (permission_string);
CREATE UNIQUE INDEX IF NOT EXISTS permissions_pkey ON public.tbl_permissions USING btree (id);
CREATE INDEX IF NOT EXISTS idx_tbl_quizzes_educator_id ON public.tbl_quizzes USING btree (educator_id);
CREATE INDEX IF NOT EXISTS idx_tbl_quizzes_module_id ON public.tbl_quizzes USING btree (module_id);
CREATE INDEX IF NOT EXISTS idx_tbl_quizzes_quiz_type ON public.tbl_quizzes USING btree (quiz_type);
CREATE INDEX IF NOT EXISTS idx_tbl_quizzes_section_id ON public.tbl_quizzes USING btree (section_id);
CREATE INDEX IF NOT EXISTS idx_tbl_quizzes_subject_id ON public.tbl_quizzes USING btree (subject_id);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_quizzes_pkey ON public.tbl_quizzes USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS role_permissions_pkey ON public.tbl_role_permissions USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS role_permissions_unique_pair ON public.tbl_role_permissions USING btree (role_id, permission_id);
CREATE UNIQUE INDEX IF NOT EXISTS roles_name_key ON public.tbl_roles USING btree (name);
CREATE UNIQUE INDEX IF NOT EXISTS roles_pkey ON public.tbl_roles USING btree (id);
CREATE INDEX IF NOT EXISTS idx_tbl_scores_module_id ON public.tbl_scores USING btree (module_id);
CREATE INDEX IF NOT EXISTS idx_tbl_scores_section_id ON public.tbl_scores USING btree (section_id);
CREATE INDEX IF NOT EXISTS idx_tbl_scores_status ON public.tbl_scores USING btree (status);
CREATE INDEX IF NOT EXISTS idx_tbl_scores_student_id ON public.tbl_scores USING btree (student_id);
CREATE INDEX IF NOT EXISTS idx_tbl_scores_student_module ON public.tbl_scores USING btree (student_id, module_id);
CREATE INDEX IF NOT EXISTS idx_tbl_scores_subject_id ON public.tbl_scores USING btree (subject_id);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_scores_pkey ON public.tbl_scores USING btree (id);
CREATE INDEX IF NOT EXISTS idx_tbl_sections_academic_term_id ON public.tbl_sections USING btree (academic_term_id);
CREATE INDEX IF NOT EXISTS idx_tbl_sections_educator_id ON public.tbl_sections USING btree (educator_id);
CREATE INDEX IF NOT EXISTS idx_tbl_sections_section_name ON public.tbl_sections USING btree (section_name);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_sections_pkey ON public.tbl_sections USING btree (id);
CREATE INDEX IF NOT EXISTS idx_tbl_sections_term_academic_term_id ON public.tbl_sections_term USING btree (academic_term_id);
CREATE INDEX IF NOT EXISTS idx_tbl_sections_term_section_id ON public.tbl_sections_term USING btree (section_id);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_sections_term_pkey ON public.tbl_sections_term USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_sections_term_unique_pair ON public.tbl_sections_term USING btree (section_id, academic_term_id);
CREATE INDEX IF NOT EXISTS idx_tbl_student_module_retakes_educator_id ON public.tbl_student_module_retakes USING btree (educator_id);
CREATE INDEX IF NOT EXISTS idx_tbl_student_module_retakes_module_id ON public.tbl_student_module_retakes USING btree (module_id);
CREATE INDEX IF NOT EXISTS idx_tbl_student_module_retakes_student_module ON public.tbl_student_module_retakes USING btree (student_id, module_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tbl_student_module_retakes_unique_pair ON public.tbl_student_module_retakes USING btree (educator_id, student_id, module_id);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_student_module_retakes_pkey ON public.tbl_student_module_retakes USING btree (id);
CREATE INDEX IF NOT EXISTS idx_tbl_student_presence_last_seen_at ON public.tbl_student_presence USING btree (last_seen_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tbl_student_presence_student_id ON public.tbl_student_presence USING btree (student_id);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_student_presence_pkey ON public.tbl_student_presence USING btree (id);
CREATE INDEX IF NOT EXISTS idx_tbl_subjects_educator_id ON public.tbl_subjects USING btree (educator_id);
CREATE INDEX IF NOT EXISTS idx_tbl_subjects_sections_id ON public.tbl_subjects USING btree (sections_id);
CREATE INDEX IF NOT EXISTS idx_tbl_subjects_subject_code ON public.tbl_subjects USING btree (subject_code);
CREATE INDEX IF NOT EXISTS idx_tbl_subjects_subject_name ON public.tbl_subjects USING btree (subject_name);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_subjects_pkey ON public.tbl_subjects USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_subjects_unique_code_per_section ON public.tbl_subjects USING btree (educator_id, sections_id, subject_code);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_subjects_unique_name_per_section ON public.tbl_subjects USING btree (educator_id, sections_id, subject_name);
CREATE INDEX IF NOT EXISTS idx_user_roles_role_id ON public.tbl_user_roles USING btree (role_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON public.tbl_user_roles USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS user_roles_pkey ON public.tbl_user_roles USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS user_roles_user_role_unique ON public.tbl_user_roles USING btree (user_id, role_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON public.tbl_users USING btree (email);
CREATE INDEX IF NOT EXISTS idx_users_user_id ON public.tbl_users USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_users_user_type ON public.tbl_users USING btree (user_type);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_key ON public.tbl_users USING btree (email);
CREATE UNIQUE INDEX IF NOT EXISTS users_pkey ON public.tbl_users USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS users_user_id_key ON public.tbl_users USING btree (user_id);


-- ==================== FUNCTIONS ====================

CREATE OR REPLACE FUNCTION public.enforce_section_term_uniqueness()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT public.validate_section_term_uniqueness(NEW.section_id, NEW.academic_term_id) THEN
    RAISE EXCEPTION 'Section name already exists in the selected academic term.';
  END IF;

  RETURN NEW;
END;
$function$;
CREATE OR REPLACE FUNCTION public.export_public_schema_data()
 RETURNS TABLE(table_name text, rows jsonb)
 LANGUAGE plpgsql
AS $function$
DECLARE
  current_table record;
  current_rows jsonb;
BEGIN
  FOR current_table IN
    SELECT tablename
    FROM pg_tables
    WHERE schemaname = 'public'
    ORDER BY tablename
  LOOP
    EXECUTE format(
      'SELECT COALESCE(jsonb_agg(to_jsonb(source_rows)), ''[]''::jsonb) FROM public.%I AS source_rows',
      current_table.tablename
    )
    INTO current_rows;

    table_name := current_table.tablename;
    rows := current_rows;
    RETURN NEXT;
  END LOOP;
END;
$function$;
CREATE OR REPLACE FUNCTION public.get_current_tbl_user_id()
 RETURNS bigint
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT id
  FROM public.tbl_users
  WHERE email = auth.email()
    AND deleted_at IS NULL
  LIMIT 1;
$function$;
CREATE OR REPLACE FUNCTION public.get_group_chat_list()
 RETURNS TABLE(group_chat_id bigint, subject_id bigint, section_id bigint, educator_id bigint, subject_name text, section_name text, student_count integer, online_student_count integer, last_message_preview text, last_message_at timestamp with time zone, last_message_sender_user_id bigint, last_message_sender_display_name text, unread_count integer)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  WITH accessible_chats AS (
    SELECT
      chats.id,
      chats.subject_id,
      chats.section_id,
      chats.educator_id,
      chats.created_at,
      subjects.subject_name,
      sections.section_name
    FROM public.tbl_group_chats AS chats
    INNER JOIN public.tbl_subjects AS subjects
      ON subjects.id = chats.subject_id
    INNER JOIN public.tbl_sections AS sections
      ON sections.id = chats.section_id
    WHERE (
      (
        public.has_role('educator')
        AND chats.educator_id = public.get_current_tbl_user_id()
      )
      OR (
        public.has_role('student')
        AND EXISTS (
          SELECT 1
          FROM public.tbl_enrolled AS enrolled
          WHERE enrolled.educator_id = chats.educator_id
            AND enrolled.subject_id = chats.subject_id
            AND enrolled.student_id = public.get_current_tbl_user_id()
            AND enrolled.is_active = TRUE
        )
      )
    )
  ),
  active_counts AS (
    SELECT
      chats.id AS group_chat_id,
      COUNT(DISTINCT enrolled.student_id)::INT AS student_count
    FROM accessible_chats AS chats
    INNER JOIN public.tbl_enrolled AS enrolled
      ON enrolled.educator_id = chats.educator_id
     AND enrolled.subject_id = chats.subject_id
     AND enrolled.is_active = TRUE
    INNER JOIN public.tbl_users AS student_user
      ON student_user.id = enrolled.student_id
     AND student_user.user_type = 'student'
     AND student_user.is_active = TRUE
     AND student_user.deleted_at IS NULL
    GROUP BY chats.id
  ),
  online_counts AS (
    SELECT
      chats.id AS group_chat_id,
      COUNT(DISTINCT presence.student_id)::INT AS online_student_count
    FROM accessible_chats AS chats
    INNER JOIN public.tbl_enrolled AS enrolled
      ON enrolled.educator_id = chats.educator_id
     AND enrolled.subject_id = chats.subject_id
     AND enrolled.is_active = TRUE
    INNER JOIN public.tbl_users AS student_user
      ON student_user.id = enrolled.student_id
     AND student_user.user_type = 'student'
     AND student_user.is_active = TRUE
     AND student_user.deleted_at IS NULL
    INNER JOIN public.tbl_student_presence AS presence
      ON presence.student_id = enrolled.student_id
     AND presence.last_seen_at >= NOW() - INTERVAL '60 seconds'
    GROUP BY chats.id
  )
  SELECT
    chats.id AS group_chat_id,
    chats.subject_id,
    chats.section_id,
    chats.educator_id,
    chats.subject_name,
    chats.section_name,
    counts.student_count,
    COALESCE(online.online_student_count, 0) AS online_student_count,
    last_message.content AS last_message_preview,
    last_message.created_at AS last_message_at,
    last_message.sender_user_id AS last_message_sender_user_id,
    last_message.sender_display_name AS last_message_sender_display_name,
    COALESCE(unread.unread_count, 0) AS unread_count
  FROM accessible_chats AS chats
  INNER JOIN active_counts AS counts
    ON counts.group_chat_id = chats.id
  LEFT JOIN online_counts AS online
    ON online.group_chat_id = chats.id
  LEFT JOIN public.tbl_group_chat_reads AS reads
    ON reads.group_chat_id = chats.id
   AND reads.user_id = public.get_current_tbl_user_id()
  LEFT JOIN LATERAL (
    SELECT
      message.content,
      message.created_at,
      message.sender_user_id,
      TRIM(CONCAT(sender_user.given_name, ' ', sender_user.surname)) AS sender_display_name
    FROM public.tbl_group_chat_messages AS message
    INNER JOIN public.tbl_users AS sender_user
      ON sender_user.id = message.sender_user_id
     AND sender_user.deleted_at IS NULL
    WHERE message.group_chat_id = chats.id
    ORDER BY message.created_at DESC, message.id DESC
    LIMIT 1
  ) AS last_message ON TRUE
  LEFT JOIN LATERAL (
    SELECT COUNT(*)::INT AS unread_count
    FROM public.tbl_group_chat_messages AS message
    WHERE message.group_chat_id = chats.id
      AND message.sender_user_id <> public.get_current_tbl_user_id()
      AND message.created_at > COALESCE(reads.last_read_at, 'epoch'::TIMESTAMPTZ)
  ) AS unread ON TRUE
  ORDER BY COALESCE(last_message.created_at, chats.created_at) DESC, chats.subject_name ASC;
$function$;
CREATE OR REPLACE FUNCTION public.get_group_chat_messages(target_group_chat_id bigint)
 RETURNS TABLE(message_id bigint, group_chat_id bigint, sender_user_id bigint, sender_display_name text, sender_role text, content text, created_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  WITH authorized_chat AS (
    SELECT chats.id
    FROM public.tbl_group_chats AS chats
    WHERE chats.id = target_group_chat_id
      AND (
        (
          public.has_role('educator')
          AND chats.educator_id = public.get_current_tbl_user_id()
        )
        OR (
          public.has_role('student')
          AND EXISTS (
            SELECT 1
            FROM public.tbl_enrolled AS enrolled
            WHERE enrolled.educator_id = chats.educator_id
              AND enrolled.subject_id = chats.subject_id
              AND enrolled.student_id = public.get_current_tbl_user_id()
              AND enrolled.is_active = TRUE
          )
        )
      )
  )
  SELECT
    message.id AS message_id,
    message.group_chat_id,
    message.sender_user_id,
    TRIM(CONCAT(sender_user.given_name, ' ', sender_user.surname)) AS sender_display_name,
    sender_user.user_type AS sender_role,
    message.content,
    message.created_at
  FROM authorized_chat
  INNER JOIN public.tbl_group_chat_messages AS message
    ON message.group_chat_id = authorized_chat.id
  INNER JOIN public.tbl_users AS sender_user
    ON sender_user.id = message.sender_user_id
   AND sender_user.deleted_at IS NULL
  ORDER BY message.created_at ASC, message.id ASC;
$function$;
CREATE OR REPLACE FUNCTION public.has_role(role_name text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM public.tbl_user_roles ur
    INNER JOIN public.tbl_roles r ON r.id = ur.role_id
    INNER JOIN public.tbl_users u ON u.id = ur.user_id
    WHERE u.email = auth.email()
      AND u.deleted_at IS NULL
      AND ur.deleted_at IS NULL
      AND r.is_active = TRUE
      AND r.name = role_name
  );
$function$;
CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;
CREATE OR REPLACE FUNCTION public.user_has_permission(required_permission text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM public.tbl_user_roles user_roles
    INNER JOIN public.tbl_roles roles
      ON roles.id = user_roles.role_id
    INNER JOIN public.tbl_role_permissions role_permissions
      ON role_permissions.role_id = roles.id
    INNER JOIN public.tbl_permissions permissions
      ON permissions.id = role_permissions.permission_id
    WHERE user_roles.user_id = public.get_current_tbl_user_id()
      AND user_roles.deleted_at IS NULL
      AND roles.is_active = TRUE
      AND permissions.is_active = TRUE
      AND permissions.permission_string = required_permission
  );
$function$;
CREATE OR REPLACE FUNCTION public.validate_section_term_uniqueness(input_section_id bigint, input_academic_term_id bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT NOT EXISTS (
    SELECT 1
    FROM public.tbl_sections current_section
    INNER JOIN public.tbl_sections_term current_term
      ON current_term.section_id = current_section.id
    INNER JOIN public.tbl_sections compare_section
      ON compare_section.educator_id = current_section.educator_id
     AND compare_section.section_name = current_section.section_name
     AND compare_section.id <> current_section.id
    INNER JOIN public.tbl_sections_term compare_term
      ON compare_term.section_id = compare_section.id
     AND compare_term.academic_term_id = input_academic_term_id
    WHERE current_section.id = input_section_id
  );
$function$;


-- ==================== TRIGGERS ====================

DROP TRIGGER IF EXISTS "trg_enforce_section_term_uniqueness" ON "public"."tbl_sections_term";
CREATE TRIGGER trg_enforce_section_term_uniqueness BEFORE INSERT OR UPDATE ON tbl_sections_term FOR EACH ROW EXECUTE FUNCTION enforce_section_term_uniqueness();


-- ==================== ROW LEVEL SECURITY ====================

ALTER TABLE "public"."tbl_academic_term" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_academic_year" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_enrolled" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_group_chat_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_group_chat_reads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_group_chats" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_learning_materials" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_modules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_permissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_quizzes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_role_permissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_roles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_scores" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_sections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_sections_term" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_student_module_retakes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_student_presence" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_subjects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_user_roles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tbl_users" ENABLE ROW LEVEL SECURITY;


-- ==================== POLICIES ====================

DROP POLICY IF EXISTS "Admin full access on tbl_academic_term" ON "public"."tbl_academic_term";
CREATE POLICY "Admin full access on tbl_academic_term" ON "public"."tbl_academic_term" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Authenticated users can read active academic terms" ON "public"."tbl_academic_term";
CREATE POLICY "Authenticated users can read active academic terms" ON "public"."tbl_academic_term" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((is_active = true));
DROP POLICY IF EXISTS "Admin full access on tbl_academic_year" ON "public"."tbl_academic_year";
CREATE POLICY "Admin full access on tbl_academic_year" ON "public"."tbl_academic_year" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Authenticated users can read active academic years" ON "public"."tbl_academic_year";
CREATE POLICY "Authenticated users can read active academic years" ON "public"."tbl_academic_year" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((is_active = true));
DROP POLICY IF EXISTS "Admin full access on tbl_enrolled" ON "public"."tbl_enrolled";
CREATE POLICY "Admin full access on tbl_enrolled" ON "public"."tbl_enrolled" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Educator enrollment create access" ON "public"."tbl_enrolled";
CREATE POLICY "Educator enrollment create access" ON "public"."tbl_enrolled" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Educator enrollment delete access" ON "public"."tbl_enrolled";
CREATE POLICY "Educator enrollment delete access" ON "public"."tbl_enrolled" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Educator enrollment update access" ON "public"."tbl_enrolled";
CREATE POLICY "Educator enrollment update access" ON "public"."tbl_enrolled" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id()))) WITH CHECK ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Educator enrollment view access" ON "public"."tbl_enrolled";
CREATE POLICY "Educator enrollment view access" ON "public"."tbl_enrolled" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Student enrollment view access" ON "public"."tbl_enrolled";
CREATE POLICY "Student enrollment view access" ON "public"."tbl_enrolled" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('student'::text) AND (student_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Admin full access on tbl_group_chat_messages" ON "public"."tbl_group_chat_messages";
CREATE POLICY "Admin full access on tbl_group_chat_messages" ON "public"."tbl_group_chat_messages" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Educator group chat message create access" ON "public"."tbl_group_chat_messages";
CREATE POLICY "Educator group chat message create access" ON "public"."tbl_group_chat_messages" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_role('educator'::text) AND (sender_user_id = get_current_tbl_user_id()) AND (EXISTS ( SELECT 1
   FROM tbl_group_chats chats
  WHERE ((chats.id = tbl_group_chat_messages.group_chat_id) AND (chats.educator_id = get_current_tbl_user_id()))))));
DROP POLICY IF EXISTS "Educator group chat message view access" ON "public"."tbl_group_chat_messages";
CREATE POLICY "Educator group chat message view access" ON "public"."tbl_group_chat_messages" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('educator'::text) AND (EXISTS ( SELECT 1
   FROM tbl_group_chats chats
  WHERE ((chats.id = tbl_group_chat_messages.group_chat_id) AND (chats.educator_id = get_current_tbl_user_id()))))));
DROP POLICY IF EXISTS "Student group chat message create access" ON "public"."tbl_group_chat_messages";
CREATE POLICY "Student group chat message create access" ON "public"."tbl_group_chat_messages" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_role('student'::text) AND (sender_user_id = get_current_tbl_user_id()) AND (EXISTS ( SELECT 1
   FROM (tbl_group_chats chats
     JOIN tbl_enrolled enrolled ON (((enrolled.educator_id = chats.educator_id) AND (enrolled.subject_id = chats.subject_id))))
  WHERE ((chats.id = tbl_group_chat_messages.group_chat_id) AND (enrolled.student_id = get_current_tbl_user_id()) AND (enrolled.is_active = true))))));
DROP POLICY IF EXISTS "Student group chat message view access" ON "public"."tbl_group_chat_messages";
CREATE POLICY "Student group chat message view access" ON "public"."tbl_group_chat_messages" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('student'::text) AND (EXISTS ( SELECT 1
   FROM (tbl_group_chats chats
     JOIN tbl_enrolled enrolled ON (((enrolled.educator_id = chats.educator_id) AND (enrolled.subject_id = chats.subject_id))))
  WHERE ((chats.id = tbl_group_chat_messages.group_chat_id) AND (enrolled.student_id = get_current_tbl_user_id()) AND (enrolled.is_active = true))))));
DROP POLICY IF EXISTS "Admin full access on tbl_group_chat_reads" ON "public"."tbl_group_chat_reads";
CREATE POLICY "Admin full access on tbl_group_chat_reads" ON "public"."tbl_group_chat_reads" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Educator group chat read view access" ON "public"."tbl_group_chat_reads";
CREATE POLICY "Educator group chat read view access" ON "public"."tbl_group_chat_reads" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('educator'::text) AND (EXISTS ( SELECT 1
   FROM tbl_group_chats chats
  WHERE ((chats.id = tbl_group_chat_reads.group_chat_id) AND (chats.educator_id = get_current_tbl_user_id()))))));
DROP POLICY IF EXISTS "Educator own group chat read create access" ON "public"."tbl_group_chat_reads";
CREATE POLICY "Educator own group chat read create access" ON "public"."tbl_group_chat_reads" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_role('educator'::text) AND (user_id = get_current_tbl_user_id()) AND (EXISTS ( SELECT 1
   FROM tbl_group_chats chats
  WHERE ((chats.id = tbl_group_chat_reads.group_chat_id) AND (chats.educator_id = get_current_tbl_user_id()))))));
DROP POLICY IF EXISTS "Educator own group chat read update access" ON "public"."tbl_group_chat_reads";
CREATE POLICY "Educator own group chat read update access" ON "public"."tbl_group_chat_reads" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((has_role('educator'::text) AND (user_id = get_current_tbl_user_id()) AND (EXISTS ( SELECT 1
   FROM tbl_group_chats chats
  WHERE ((chats.id = tbl_group_chat_reads.group_chat_id) AND (chats.educator_id = get_current_tbl_user_id())))))) WITH CHECK ((has_role('educator'::text) AND (user_id = get_current_tbl_user_id()) AND (EXISTS ( SELECT 1
   FROM tbl_group_chats chats
  WHERE ((chats.id = tbl_group_chat_reads.group_chat_id) AND (chats.educator_id = get_current_tbl_user_id()))))));
DROP POLICY IF EXISTS "Student group chat read view access" ON "public"."tbl_group_chat_reads";
CREATE POLICY "Student group chat read view access" ON "public"."tbl_group_chat_reads" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('student'::text) AND (EXISTS ( SELECT 1
   FROM (tbl_group_chats chats
     JOIN tbl_enrolled enrolled ON (((enrolled.educator_id = chats.educator_id) AND (enrolled.subject_id = chats.subject_id))))
  WHERE ((chats.id = tbl_group_chat_reads.group_chat_id) AND (enrolled.student_id = get_current_tbl_user_id()) AND (enrolled.is_active = true))))));
DROP POLICY IF EXISTS "Student own group chat read create access" ON "public"."tbl_group_chat_reads";
CREATE POLICY "Student own group chat read create access" ON "public"."tbl_group_chat_reads" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_role('student'::text) AND (user_id = get_current_tbl_user_id()) AND (EXISTS ( SELECT 1
   FROM (tbl_group_chats chats
     JOIN tbl_enrolled enrolled ON (((enrolled.educator_id = chats.educator_id) AND (enrolled.subject_id = chats.subject_id))))
  WHERE ((chats.id = tbl_group_chat_reads.group_chat_id) AND (enrolled.student_id = get_current_tbl_user_id()) AND (enrolled.is_active = true))))));
DROP POLICY IF EXISTS "Student own group chat read update access" ON "public"."tbl_group_chat_reads";
CREATE POLICY "Student own group chat read update access" ON "public"."tbl_group_chat_reads" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((has_role('student'::text) AND (user_id = get_current_tbl_user_id()) AND (EXISTS ( SELECT 1
   FROM (tbl_group_chats chats
     JOIN tbl_enrolled enrolled ON (((enrolled.educator_id = chats.educator_id) AND (enrolled.subject_id = chats.subject_id))))
  WHERE ((chats.id = tbl_group_chat_reads.group_chat_id) AND (enrolled.student_id = get_current_tbl_user_id()) AND (enrolled.is_active = true)))))) WITH CHECK ((has_role('student'::text) AND (user_id = get_current_tbl_user_id()) AND (EXISTS ( SELECT 1
   FROM (tbl_group_chats chats
     JOIN tbl_enrolled enrolled ON (((enrolled.educator_id = chats.educator_id) AND (enrolled.subject_id = chats.subject_id))))
  WHERE ((chats.id = tbl_group_chat_reads.group_chat_id) AND (enrolled.student_id = get_current_tbl_user_id()) AND (enrolled.is_active = true))))));
DROP POLICY IF EXISTS "Admin full access on tbl_group_chats" ON "public"."tbl_group_chats";
CREATE POLICY "Admin full access on tbl_group_chats" ON "public"."tbl_group_chats" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Educator group chat create access" ON "public"."tbl_group_chats";
CREATE POLICY "Educator group chat create access" ON "public"."tbl_group_chats" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id()) AND (EXISTS ( SELECT 1
   FROM tbl_subjects subject_row
  WHERE ((subject_row.id = tbl_group_chats.subject_id) AND (subject_row.educator_id = get_current_tbl_user_id()) AND (subject_row.sections_id = tbl_group_chats.section_id))))));
DROP POLICY IF EXISTS "Educator group chat delete access" ON "public"."tbl_group_chats";
CREATE POLICY "Educator group chat delete access" ON "public"."tbl_group_chats" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Educator group chat view access" ON "public"."tbl_group_chats";
CREATE POLICY "Educator group chat view access" ON "public"."tbl_group_chats" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Student group chat view access" ON "public"."tbl_group_chats";
CREATE POLICY "Student group chat view access" ON "public"."tbl_group_chats" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('student'::text) AND (EXISTS ( SELECT 1
   FROM tbl_enrolled enrolled
  WHERE ((enrolled.educator_id = tbl_group_chats.educator_id) AND (enrolled.subject_id = tbl_group_chats.subject_id) AND (enrolled.student_id = get_current_tbl_user_id()) AND (enrolled.is_active = true))))));
DROP POLICY IF EXISTS "Educator learning material create access" ON "public"."tbl_learning_materials";
CREATE POLICY "Educator learning material create access" ON "public"."tbl_learning_materials" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Educator learning material delete access" ON "public"."tbl_learning_materials";
CREATE POLICY "Educator learning material delete access" ON "public"."tbl_learning_materials" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Educator learning material update access" ON "public"."tbl_learning_materials";
CREATE POLICY "Educator learning material update access" ON "public"."tbl_learning_materials" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id()))) WITH CHECK ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Educator learning material view access" ON "public"."tbl_learning_materials";
CREATE POLICY "Educator learning material view access" ON "public"."tbl_learning_materials" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Student learning material view access" ON "public"."tbl_learning_materials";
CREATE POLICY "Student learning material view access" ON "public"."tbl_learning_materials" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('student'::text) AND (is_active = true) AND (EXISTS ( SELECT 1
   FROM tbl_enrolled enrolled
  WHERE ((enrolled.student_id = get_current_tbl_user_id()) AND (enrolled.educator_id = tbl_learning_materials.educator_id) AND (enrolled.subject_id = tbl_learning_materials.subject_id) AND (enrolled.is_active = true))))));
DROP POLICY IF EXISTS "Educator module create access" ON "public"."tbl_modules";
CREATE POLICY "Educator module create access" ON "public"."tbl_modules" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Educator module delete access" ON "public"."tbl_modules";
CREATE POLICY "Educator module delete access" ON "public"."tbl_modules" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Educator module update access" ON "public"."tbl_modules";
CREATE POLICY "Educator module update access" ON "public"."tbl_modules" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id()))) WITH CHECK ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Educator module view access" ON "public"."tbl_modules";
CREATE POLICY "Educator module view access" ON "public"."tbl_modules" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Student module view access" ON "public"."tbl_modules";
CREATE POLICY "Student module view access" ON "public"."tbl_modules" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('student'::text) AND (EXISTS ( SELECT 1
   FROM tbl_enrolled enrolled
  WHERE ((enrolled.student_id = get_current_tbl_user_id()) AND (enrolled.educator_id = tbl_modules.educator_id) AND (enrolled.subject_id = tbl_modules.subject_id) AND (enrolled.is_active = true))))));
DROP POLICY IF EXISTS "Admin full access on tbl_notifications" ON "public"."tbl_notifications";
CREATE POLICY "Admin full access on tbl_notifications" ON "public"."tbl_notifications" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Educator notification insert access" ON "public"."tbl_notifications";
CREATE POLICY "Educator notification insert access" ON "public"."tbl_notifications" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_role('educator'::text) AND (actor_user_id = get_current_tbl_user_id()) AND (event_type = ANY (ARRAY['module_created'::text, 'module_updated'::text, 'module_deleted'::text, 'learning_material_uploaded'::text, 'learning_material_deleted'::text, 'quiz_created'::text, 'quiz_uploaded'::text, 'quiz_updated'::text, 'quiz_deleted'::text, 'enrollment_created'::text, 'enrollment_updated'::text, 'enrollment_deleted'::text, 'retake_updated'::text])) AND (EXISTS ( SELECT 1
   FROM tbl_users student_user
  WHERE ((student_user.id = tbl_notifications.recipient_user_id) AND (student_user.user_type = 'student'::text) AND (student_user.deleted_at IS NULL)))) AND (((event_type = 'enrollment_deleted'::text) AND (EXISTS ( SELECT 1
   FROM tbl_subjects subject_row
  WHERE ((subject_row.id = tbl_notifications.subject_id) AND (subject_row.educator_id = get_current_tbl_user_id()))))) OR ((event_type <> 'enrollment_deleted'::text) AND (EXISTS ( SELECT 1
   FROM tbl_enrolled enrolled
  WHERE ((enrolled.educator_id = get_current_tbl_user_id()) AND (enrolled.student_id = tbl_notifications.recipient_user_id) AND (enrolled.subject_id = tbl_notifications.subject_id))))))));
DROP POLICY IF EXISTS "Recipients can update own notifications" ON "public"."tbl_notifications";
CREATE POLICY "Recipients can update own notifications" ON "public"."tbl_notifications" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((recipient_user_id = get_current_tbl_user_id())) WITH CHECK ((recipient_user_id = get_current_tbl_user_id()));
DROP POLICY IF EXISTS "Recipients can view own notifications" ON "public"."tbl_notifications";
CREATE POLICY "Recipients can view own notifications" ON "public"."tbl_notifications" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((recipient_user_id = get_current_tbl_user_id()));
DROP POLICY IF EXISTS "Student submission notification insert access" ON "public"."tbl_notifications";
CREATE POLICY "Student submission notification insert access" ON "public"."tbl_notifications" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_role('student'::text) AND (actor_user_id = get_current_tbl_user_id()) AND (event_type = 'quiz_submitted'::text) AND (EXISTS ( SELECT 1
   FROM (tbl_modules module_row
     JOIN tbl_enrolled enrolled ON (((enrolled.educator_id = module_row.educator_id) AND (enrolled.subject_id = module_row.subject_id))))
  WHERE ((module_row.id = tbl_notifications.module_id) AND (module_row.educator_id = tbl_notifications.recipient_user_id) AND (enrolled.student_id = get_current_tbl_user_id()) AND (enrolled.is_active = true))))));
DROP POLICY IF EXISTS "Admin full access on tbl_permissions" ON "public"."tbl_permissions";
CREATE POLICY "Admin full access on tbl_permissions" ON "public"."tbl_permissions" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Authenticated users can read active permissions" ON "public"."tbl_permissions";
CREATE POLICY "Authenticated users can read active permissions" ON "public"."tbl_permissions" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((is_active = true));
DROP POLICY IF EXISTS "Educator quiz create access" ON "public"."tbl_quizzes";
CREATE POLICY "Educator quiz create access" ON "public"."tbl_quizzes" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Educator quiz delete access" ON "public"."tbl_quizzes";
CREATE POLICY "Educator quiz delete access" ON "public"."tbl_quizzes" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Educator quiz update access" ON "public"."tbl_quizzes";
CREATE POLICY "Educator quiz update access" ON "public"."tbl_quizzes" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id()))) WITH CHECK ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Educator quiz view access" ON "public"."tbl_quizzes";
CREATE POLICY "Educator quiz view access" ON "public"."tbl_quizzes" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Student quiz view access" ON "public"."tbl_quizzes";
CREATE POLICY "Student quiz view access" ON "public"."tbl_quizzes" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('student'::text) AND (EXISTS ( SELECT 1
   FROM tbl_enrolled enrolled
  WHERE ((enrolled.student_id = get_current_tbl_user_id()) AND (enrolled.educator_id = tbl_quizzes.educator_id) AND (enrolled.subject_id = tbl_quizzes.subject_id) AND (enrolled.is_active = true))))));
DROP POLICY IF EXISTS "Admin full access on tbl_role_permissions" ON "public"."tbl_role_permissions";
CREATE POLICY "Admin full access on tbl_role_permissions" ON "public"."tbl_role_permissions" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Authenticated users can read role permissions" ON "public"."tbl_role_permissions";
CREATE POLICY "Authenticated users can read role permissions" ON "public"."tbl_role_permissions" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
DROP POLICY IF EXISTS "Admin full access on tbl_roles" ON "public"."tbl_roles";
CREATE POLICY "Admin full access on tbl_roles" ON "public"."tbl_roles" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Authenticated users can read active roles" ON "public"."tbl_roles";
CREATE POLICY "Authenticated users can read active roles" ON "public"."tbl_roles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((is_active = true));
DROP POLICY IF EXISTS "Admin full access on tbl_scores" ON "public"."tbl_scores";
CREATE POLICY "Admin full access on tbl_scores" ON "public"."tbl_scores" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Educator score view access" ON "public"."tbl_scores";
CREATE POLICY "Educator score view access" ON "public"."tbl_scores" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Student score create access" ON "public"."tbl_scores";
CREATE POLICY "Student score create access" ON "public"."tbl_scores" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_role('student'::text) AND (student_id = get_current_tbl_user_id()) AND (EXISTS ( SELECT 1
   FROM tbl_enrolled enrolled
  WHERE ((enrolled.student_id = tbl_scores.student_id) AND (enrolled.educator_id = tbl_scores.educator_id) AND (enrolled.subject_id = tbl_scores.subject_id) AND (enrolled.is_active = true))))));
DROP POLICY IF EXISTS "Student score update access" ON "public"."tbl_scores";
CREATE POLICY "Student score update access" ON "public"."tbl_scores" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((has_role('student'::text) AND (student_id = get_current_tbl_user_id()))) WITH CHECK ((has_role('student'::text) AND (student_id = get_current_tbl_user_id()) AND (EXISTS ( SELECT 1
   FROM tbl_enrolled enrolled
  WHERE ((enrolled.student_id = tbl_scores.student_id) AND (enrolled.educator_id = tbl_scores.educator_id) AND (enrolled.subject_id = tbl_scores.subject_id) AND (enrolled.is_active = true))))));
DROP POLICY IF EXISTS "Student score view access" ON "public"."tbl_scores";
CREATE POLICY "Student score view access" ON "public"."tbl_scores" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('student'::text) AND (student_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Admin full access on tbl_sections" ON "public"."tbl_sections";
CREATE POLICY "Admin full access on tbl_sections" ON "public"."tbl_sections" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Educator section create access" ON "public"."tbl_sections";
CREATE POLICY "Educator section create access" ON "public"."tbl_sections" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id()) AND user_has_permission('sections:create'::text)));
DROP POLICY IF EXISTS "Educator section delete access" ON "public"."tbl_sections";
CREATE POLICY "Educator section delete access" ON "public"."tbl_sections" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id()) AND user_has_permission('sections:delete'::text)));
DROP POLICY IF EXISTS "Educator section update access" ON "public"."tbl_sections";
CREATE POLICY "Educator section update access" ON "public"."tbl_sections" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id()) AND user_has_permission('sections:update'::text))) WITH CHECK ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id()) AND user_has_permission('sections:update'::text)));
DROP POLICY IF EXISTS "Educator section view access" ON "public"."tbl_sections";
CREATE POLICY "Educator section view access" ON "public"."tbl_sections" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id()) AND user_has_permission('sections:view'::text)));
DROP POLICY IF EXISTS "Student section view access" ON "public"."tbl_sections";
CREATE POLICY "Student section view access" ON "public"."tbl_sections" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('student'::text) AND (EXISTS ( SELECT 1
   FROM (tbl_enrolled enrolled
     JOIN tbl_subjects subject ON ((subject.id = enrolled.subject_id)))
  WHERE ((enrolled.student_id = get_current_tbl_user_id()) AND (enrolled.educator_id = tbl_sections.educator_id) AND (subject.sections_id = tbl_sections.id) AND (enrolled.is_active = true))))));
DROP POLICY IF EXISTS "Admin full access on tbl_sections_term" ON "public"."tbl_sections_term";
CREATE POLICY "Admin full access on tbl_sections_term" ON "public"."tbl_sections_term" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Educator section term create access" ON "public"."tbl_sections_term";
CREATE POLICY "Educator section term create access" ON "public"."tbl_sections_term" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_role('educator'::text) AND user_has_permission('sections:create'::text) AND (EXISTS ( SELECT 1
   FROM tbl_sections
  WHERE ((tbl_sections.id = tbl_sections_term.section_id) AND (tbl_sections.educator_id = get_current_tbl_user_id()))))));
DROP POLICY IF EXISTS "Educator section term delete access" ON "public"."tbl_sections_term";
CREATE POLICY "Educator section term delete access" ON "public"."tbl_sections_term" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((has_role('educator'::text) AND user_has_permission('sections:delete'::text) AND (EXISTS ( SELECT 1
   FROM tbl_sections
  WHERE ((tbl_sections.id = tbl_sections_term.section_id) AND (tbl_sections.educator_id = get_current_tbl_user_id()))))));
DROP POLICY IF EXISTS "Educator section term update access" ON "public"."tbl_sections_term";
CREATE POLICY "Educator section term update access" ON "public"."tbl_sections_term" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((has_role('educator'::text) AND user_has_permission('sections:update'::text) AND (EXISTS ( SELECT 1
   FROM tbl_sections
  WHERE ((tbl_sections.id = tbl_sections_term.section_id) AND (tbl_sections.educator_id = get_current_tbl_user_id())))))) WITH CHECK ((has_role('educator'::text) AND user_has_permission('sections:update'::text) AND (EXISTS ( SELECT 1
   FROM tbl_sections
  WHERE ((tbl_sections.id = tbl_sections_term.section_id) AND (tbl_sections.educator_id = get_current_tbl_user_id()))))));
DROP POLICY IF EXISTS "Educator section term view access" ON "public"."tbl_sections_term";
CREATE POLICY "Educator section term view access" ON "public"."tbl_sections_term" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('educator'::text) AND user_has_permission('sections:view'::text) AND (EXISTS ( SELECT 1
   FROM tbl_sections
  WHERE ((tbl_sections.id = tbl_sections_term.section_id) AND (tbl_sections.educator_id = get_current_tbl_user_id()))))));
DROP POLICY IF EXISTS "Admin full access on tbl_student_module_retakes" ON "public"."tbl_student_module_retakes";
CREATE POLICY "Admin full access on tbl_student_module_retakes" ON "public"."tbl_student_module_retakes" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Educator student retake create access" ON "public"."tbl_student_module_retakes";
CREATE POLICY "Educator student retake create access" ON "public"."tbl_student_module_retakes" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Educator student retake delete access" ON "public"."tbl_student_module_retakes";
CREATE POLICY "Educator student retake delete access" ON "public"."tbl_student_module_retakes" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Educator student retake update access" ON "public"."tbl_student_module_retakes";
CREATE POLICY "Educator student retake update access" ON "public"."tbl_student_module_retakes" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id()))) WITH CHECK ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Educator student retake view access" ON "public"."tbl_student_module_retakes";
CREATE POLICY "Educator student retake view access" ON "public"."tbl_student_module_retakes" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Student retake grant view access" ON "public"."tbl_student_module_retakes";
CREATE POLICY "Student retake grant view access" ON "public"."tbl_student_module_retakes" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('student'::text) AND (student_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Admin full access on tbl_student_presence" ON "public"."tbl_student_presence";
CREATE POLICY "Admin full access on tbl_student_presence" ON "public"."tbl_student_presence" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Educator student presence view access" ON "public"."tbl_student_presence";
CREATE POLICY "Educator student presence view access" ON "public"."tbl_student_presence" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('educator'::text) AND (EXISTS ( SELECT 1
   FROM tbl_enrolled enrolled
  WHERE ((enrolled.student_id = tbl_student_presence.student_id) AND (enrolled.educator_id = get_current_tbl_user_id()) AND (enrolled.is_active = true))))));
DROP POLICY IF EXISTS "Student own presence create access" ON "public"."tbl_student_presence";
CREATE POLICY "Student own presence create access" ON "public"."tbl_student_presence" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_role('student'::text) AND (student_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Student own presence delete access" ON "public"."tbl_student_presence";
CREATE POLICY "Student own presence delete access" ON "public"."tbl_student_presence" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((has_role('student'::text) AND (student_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Student own presence update access" ON "public"."tbl_student_presence";
CREATE POLICY "Student own presence update access" ON "public"."tbl_student_presence" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((has_role('student'::text) AND (student_id = get_current_tbl_user_id()))) WITH CHECK ((has_role('student'::text) AND (student_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Student own presence view access" ON "public"."tbl_student_presence";
CREATE POLICY "Student own presence view access" ON "public"."tbl_student_presence" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('student'::text) AND (student_id = get_current_tbl_user_id())));
DROP POLICY IF EXISTS "Admin full access on tbl_subjects" ON "public"."tbl_subjects";
CREATE POLICY "Admin full access on tbl_subjects" ON "public"."tbl_subjects" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Educator subject create access" ON "public"."tbl_subjects";
CREATE POLICY "Educator subject create access" ON "public"."tbl_subjects" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id()) AND user_has_permission('subjects:create'::text)));
DROP POLICY IF EXISTS "Educator subject delete access" ON "public"."tbl_subjects";
CREATE POLICY "Educator subject delete access" ON "public"."tbl_subjects" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id()) AND user_has_permission('subjects:delete'::text)));
DROP POLICY IF EXISTS "Educator subject update access" ON "public"."tbl_subjects";
CREATE POLICY "Educator subject update access" ON "public"."tbl_subjects" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id()) AND user_has_permission('subjects:update'::text))) WITH CHECK ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id()) AND user_has_permission('subjects:update'::text)));
DROP POLICY IF EXISTS "Educator subject view access" ON "public"."tbl_subjects";
CREATE POLICY "Educator subject view access" ON "public"."tbl_subjects" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('educator'::text) AND (educator_id = get_current_tbl_user_id()) AND user_has_permission('subjects:view'::text)));
DROP POLICY IF EXISTS "Student subject view access" ON "public"."tbl_subjects";
CREATE POLICY "Student subject view access" ON "public"."tbl_subjects" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('student'::text) AND (EXISTS ( SELECT 1
   FROM tbl_enrolled enrolled
  WHERE ((enrolled.student_id = get_current_tbl_user_id()) AND (enrolled.educator_id = tbl_subjects.educator_id) AND (enrolled.subject_id = tbl_subjects.id) AND (enrolled.is_active = true))))));
DROP POLICY IF EXISTS "Admin full access on tbl_user_roles" ON "public"."tbl_user_roles";
CREATE POLICY "Admin full access on tbl_user_roles" ON "public"."tbl_user_roles" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Users can read own role links" ON "public"."tbl_user_roles";
CREATE POLICY "Users can read own role links" ON "public"."tbl_user_roles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = get_current_tbl_user_id()));
DROP POLICY IF EXISTS "Admin full access on tbl_users" ON "public"."tbl_users";
CREATE POLICY "Admin full access on tbl_users" ON "public"."tbl_users" AS PERMISSIVE FOR ALL TO "authenticated" USING (has_role('admin'::text)) WITH CHECK (has_role('admin'::text));
DROP POLICY IF EXISTS "Educators can read students for enrollment" ON "public"."tbl_users";
CREATE POLICY "Educators can read students for enrollment" ON "public"."tbl_users" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('educator'::text) AND (user_type = 'student'::text) AND (deleted_at IS NULL)));
DROP POLICY IF EXISTS "Students can read assessment educators" ON "public"."tbl_users";
CREATE POLICY "Students can read assessment educators" ON "public"."tbl_users" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role('student'::text) AND (user_type = 'educator'::text) AND (deleted_at IS NULL) AND (EXISTS ( SELECT 1
   FROM tbl_enrolled enrolled
  WHERE ((enrolled.student_id = get_current_tbl_user_id()) AND (enrolled.educator_id = tbl_users.id) AND (enrolled.is_active = true))))));
DROP POLICY IF EXISTS "Users can read own profile" ON "public"."tbl_users";
CREATE POLICY "Users can read own profile" ON "public"."tbl_users" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((email = auth.email()));
DROP POLICY IF EXISTS "Users can update own profile" ON "public"."tbl_users";
CREATE POLICY "Users can update own profile" ON "public"."tbl_users" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (((id = get_current_tbl_user_id()) AND (deleted_at IS NULL))) WITH CHECK (((id = get_current_tbl_user_id()) AND (deleted_at IS NULL)));


-- ==================== PUBLICATIONS ====================

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tbl_academic_term";
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tbl_academic_year";
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tbl_enrolled";
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tbl_group_chat_messages";
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tbl_group_chat_reads";
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tbl_learning_materials";
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tbl_modules";
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tbl_notifications";
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tbl_quizzes";
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tbl_scores";
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tbl_sections";
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tbl_sections_term";
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tbl_student_module_retakes";
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tbl_student_presence";
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tbl_subjects";
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tbl_user_roles";
ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tbl_users";
