-- ==================== CREATE SECTIONS TABLE ====================
CREATE TABLE IF NOT EXISTS public.tbl_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  educator_id BIGINT NOT NULL REFERENCES public.tbl_users(id) ON DELETE CASCADE,
  academic_term_id BIGINT NOT NULL REFERENCES public.tbl_academic_term(id) ON DELETE RESTRICT,
  section_name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tbl_sections_educator_id ON public.tbl_sections(educator_id);
CREATE INDEX IF NOT EXISTS idx_tbl_sections_academic_term_id ON public.tbl_sections(academic_term_id);
CREATE INDEX IF NOT EXISTS idx_tbl_sections_section_name ON public.tbl_sections(section_name);

-- ==================== CREATE SECTIONS TERM JUNCTION TABLE ====================
CREATE TABLE IF NOT EXISTS public.tbl_sections_term (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_id BIGINT NOT NULL REFERENCES public.tbl_sections(id) ON DELETE CASCADE,
  academic_term_id BIGINT NOT NULL REFERENCES public.tbl_academic_term(id) ON DELETE CASCADE,
  CONSTRAINT tbl_sections_term_unique_pair UNIQUE (section_id, academic_term_id)
);

CREATE INDEX IF NOT EXISTS idx_tbl_sections_term_section_id ON public.tbl_sections_term(section_id);
CREATE INDEX IF NOT EXISTS idx_tbl_sections_term_academic_term_id ON public.tbl_sections_term(academic_term_id);

-- ==================== ENABLE RLS ON SECTIONS TABLES ====================
ALTER TABLE public.tbl_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tbl_sections_term ENABLE ROW LEVEL SECURITY;

-- ==================== CREATE SECTION TERM UNIQUENESS CHECK FUNCTION ====================
CREATE OR REPLACE FUNCTION public.validate_section_term_uniqueness(
  input_section_id BIGINT,
  input_academic_term_id BIGINT
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT NOT EXISTS (
    SELECT 1
    FROM public.tbl_sections current_section
    INNER JOIN public.tbl_sections_term current_term
      ON current_term.section_id = current_section.id
    INNER JOIN public.tbl_sections compare_section
      ON compare_section.educator_id = current_section.educator_id
     AND compare_section.section_name = current_section.section_name
     AND compare_section.id <> current_section.id
    INNER JOIN public.tbl_sections_term compare_term
      ON compare_term.section_id = compare_section.id
     AND compare_term.academic_term_id = input_academic_term_id
    WHERE current_section.id = input_section_id
  );
$$;

GRANT EXECUTE ON FUNCTION public.validate_section_term_uniqueness(BIGINT, BIGINT) TO authenticated;

-- ==================== CREATE SECTION TERM UNIQUENESS TRIGGER FUNCTION ====================
CREATE OR REPLACE FUNCTION public.enforce_section_term_uniqueness()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.validate_section_term_uniqueness(NEW.section_id, NEW.academic_term_id) THEN
    RAISE EXCEPTION 'Section name already exists in the selected academic term.';
  END IF;

  RETURN NEW;
END;
$$;

-- ==================== ATTACH SECTION TERM UNIQUENESS TRIGGER ====================
DROP TRIGGER IF EXISTS trg_enforce_section_term_uniqueness ON public.tbl_sections_term;

CREATE TRIGGER trg_enforce_section_term_uniqueness
BEFORE INSERT OR UPDATE ON public.tbl_sections_term
FOR EACH ROW
EXECUTE FUNCTION public.enforce_section_term_uniqueness();

-- ==================== ALLOW ADMIN FULL ACCESS TO SECTIONS ====================
DROP POLICY IF EXISTS "Admin full access on tbl_sections" ON public.tbl_sections;
CREATE POLICY "Admin full access on tbl_sections"
ON public.tbl_sections
FOR ALL
TO authenticated
USING (public.has_role('admin'))
WITH CHECK (public.has_role('admin'));

-- ==================== ALLOW EDUCATOR OWN ACCESS TO SECTIONS ====================
DROP POLICY IF EXISTS "Educator own access on tbl_sections" ON public.tbl_sections;
CREATE POLICY "Educator own access on tbl_sections"
ON public.tbl_sections
FOR ALL
TO authenticated
USING (
  public.has_role('educator')
  AND educator_id = public.get_current_tbl_user_id()
)
WITH CHECK (
  public.has_role('educator')
  AND educator_id = public.get_current_tbl_user_id()
);

-- ==================== ALLOW ADMIN FULL ACCESS TO SECTION TERMS ====================
DROP POLICY IF EXISTS "Admin full access on tbl_sections_term" ON public.tbl_sections_term;
CREATE POLICY "Admin full access on tbl_sections_term"
ON public.tbl_sections_term
FOR ALL
TO authenticated
USING (public.has_role('admin'))
WITH CHECK (public.has_role('admin'));

-- ==================== ALLOW EDUCATOR OWN ACCESS TO SECTION TERMS ====================
DROP POLICY IF EXISTS "Educator own access on tbl_sections_term" ON public.tbl_sections_term;
CREATE POLICY "Educator own access on tbl_sections_term"
ON public.tbl_sections_term
FOR ALL
TO authenticated
USING (
  public.has_role('educator')
  AND EXISTS (
    SELECT 1
    FROM public.tbl_sections
    WHERE tbl_sections.id = tbl_sections_term.section_id
      AND tbl_sections.educator_id = public.get_current_tbl_user_id()
  )
)
WITH CHECK (
  public.has_role('educator')
  AND EXISTS (
    SELECT 1
    FROM public.tbl_sections
    WHERE tbl_sections.id = tbl_sections_term.section_id
      AND tbl_sections.educator_id = public.get_current_tbl_user_id()
  )
);

-- ==================== ENABLE REAL-TIME ON SECTIONS TABLES ====================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'tbl_sections'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.tbl_sections;
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'tbl_sections_term'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.tbl_sections_term;
  END IF;
END;
$$;

-- ==================== CREATE SUBJECTS TABLE ====================
CREATE TABLE IF NOT EXISTS public.tbl_subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  educator_id BIGINT NOT NULL REFERENCES public.tbl_users(id) ON DELETE CASCADE,
  sections_id BIGINT NOT NULL REFERENCES public.tbl_sections(id) ON DELETE CASCADE,
  subject_code TEXT NOT NULL,
  subject_name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT tbl_subjects_unique_code_per_section UNIQUE (educator_id, sections_id, subject_code),
  CONSTRAINT tbl_subjects_unique_name_per_section UNIQUE (educator_id, sections_id, subject_name)
);

CREATE INDEX IF NOT EXISTS idx_tbl_subjects_educator_id ON public.tbl_subjects(educator_id);
CREATE INDEX IF NOT EXISTS idx_tbl_subjects_sections_id ON public.tbl_subjects(sections_id);
CREATE INDEX IF NOT EXISTS idx_tbl_subjects_subject_code ON public.tbl_subjects(subject_code);
CREATE INDEX IF NOT EXISTS idx_tbl_subjects_subject_name ON public.tbl_subjects(subject_name);

-- ==================== ENABLE RLS ON SUBJECTS TABLE ====================
ALTER TABLE public.tbl_subjects ENABLE ROW LEVEL SECURITY;

-- ==================== ALLOW ADMIN FULL ACCESS TO SUBJECTS ====================
DROP POLICY IF EXISTS "Admin full access on tbl_subjects" ON public.tbl_subjects;
CREATE POLICY "Admin full access on tbl_subjects"
ON public.tbl_subjects
FOR ALL
TO authenticated
USING (public.has_role('admin'))
WITH CHECK (public.has_role('admin'));

-- ==================== ALLOW EDUCATOR OWN ACCESS TO SUBJECTS ====================
DROP POLICY IF EXISTS "Educator own access on tbl_subjects" ON public.tbl_subjects;
CREATE POLICY "Educator own access on tbl_subjects"
ON public.tbl_subjects
FOR ALL
TO authenticated
USING (
  public.has_role('educator')
  AND educator_id = public.get_current_tbl_user_id()
)
WITH CHECK (
  public.has_role('educator')
  AND educator_id = public.get_current_tbl_user_id()
);

-- ==================== ENABLE REAL-TIME ON SUBJECTS TABLE ====================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'tbl_subjects'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.tbl_subjects;
  END IF;
END;
$$;
