-- ==================== CREATE TBL_GROUP_CHATS TABLE ====================
-- File: database/sql/tables/create_tbl_group_chats_table.sql
-- Created: 2026-04-03
-- Purpose: Store one shared subject and section group chat for each educator classroom.

CREATE TABLE IF NOT EXISTS public.tbl_group_chats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  educator_id BIGINT NOT NULL REFERENCES public.tbl_users(id) ON DELETE CASCADE,
  subject_id BIGINT NOT NULL REFERENCES public.tbl_subjects(id) ON DELETE CASCADE,
  section_id BIGINT NOT NULL REFERENCES public.tbl_sections(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT tbl_group_chats_unique_classroom UNIQUE (educator_id, subject_id, section_id)
);

-- Enable RLS
ALTER TABLE public.tbl_group_chats ENABLE ROW LEVEL SECURITY;
