-- ==================== CREATE TBL_NOTIFICATIONS TABLE ====================
-- File: database/sql/tables/create_tbl_notifications_table.sql
-- Created: 2026-04-03
-- Purpose: Store educator and student dashboard notifications for real-time updates.

CREATE TABLE IF NOT EXISTS public.tbl_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_user_id BIGINT NOT NULL REFERENCES public.tbl_users(id) ON DELETE CASCADE,
  actor_user_id BIGINT NOT NULL REFERENCES public.tbl_users(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  link_path TEXT,
  module_id BIGINT REFERENCES public.tbl_modules(id) ON DELETE SET NULL,
  subject_id BIGINT REFERENCES public.tbl_subjects(id) ON DELETE SET NULL,
  section_id BIGINT REFERENCES public.tbl_sections(id) ON DELETE SET NULL,
  metadata JSONB,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT tbl_notifications_event_type_check CHECK (
    event_type = ANY (
      ARRAY[
        'module_created'::TEXT,
        'module_updated'::TEXT,
        'module_deleted'::TEXT,
        'quiz_created'::TEXT,
        'quiz_uploaded'::TEXT,
        'quiz_updated'::TEXT,
        'quiz_deleted'::TEXT,
        'enrollment_created'::TEXT,
        'enrollment_updated'::TEXT,
        'enrollment_deleted'::TEXT,
        'retake_updated'::TEXT,
        'quiz_submitted'::TEXT
      ]
    )
  )
);

-- Enable RLS
ALTER TABLE public.tbl_notifications ENABLE ROW LEVEL SECURITY;
