-- ==================== CREATE TBL_GROUP_CHAT_READS TABLE ====================
-- File: database/sql/tables/create_tbl_group_chat_reads_table.sql
-- Created: 2026-04-03
-- Purpose: Track each member's latest read timestamp for unread badge counts.

CREATE TABLE IF NOT EXISTS public.tbl_group_chat_reads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_chat_id BIGINT NOT NULL REFERENCES public.tbl_group_chats(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES public.tbl_users(id) ON DELETE CASCADE,
  last_read_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT tbl_group_chat_reads_unique_pair UNIQUE (group_chat_id, user_id)
);

-- Enable RLS
ALTER TABLE public.tbl_group_chat_reads ENABLE ROW LEVEL SECURITY;
