-- ==================== CREATE TBL_LEARNING_MATERIALS TABLE ====================
-- File: database/sql/tables/create_tbl_learning_materials_table.sql
-- Created: 2026-04-07
-- Purpose: Store educator learning material uploads by subject and section.

CREATE TABLE IF NOT EXISTS public.tbl_learning_materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  educator_id BIGINT NOT NULL REFERENCES public.tbl_users(id) ON DELETE CASCADE,
  subject_id BIGINT NOT NULL REFERENCES public.tbl_subjects(id) ON DELETE CASCADE,
  section_id BIGINT NOT NULL REFERENCES public.tbl_sections(id) ON DELETE CASCADE,
  storage_bucket TEXT NOT NULL DEFAULT 'learning-materials',
  storage_path TEXT NOT NULL,
  file_name TEXT NOT NULL,
  file_extension TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  file_size BIGINT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.tbl_learning_materials ENABLE ROW LEVEL SECURITY;
