-- ==================== CREATE TBL_QUIZZES TABLE ====================
-- File: database/sql/tables/create_tbl_quizzes_table.sql
-- Created: 2026-03-30
-- Purpose: Create educator quiz items for assessment modules

CREATE TABLE IF NOT EXISTS public.tbl_quizzes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_id BIGINT NOT NULL REFERENCES public.tbl_modules(id) ON DELETE CASCADE,
  subject_id BIGINT NOT NULL REFERENCES public.tbl_subjects(id) ON DELETE CASCADE,
  section_id BIGINT NOT NULL REFERENCES public.tbl_sections(id) ON DELETE CASCADE,
  educator_id BIGINT NOT NULL REFERENCES public.tbl_users(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  quiz_type TEXT NOT NULL CHECK (quiz_type IN ('multiple_choice', 'identification')),
  choices JSONB,
  correct_answer TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.tbl_quizzes ENABLE ROW LEVEL SECURITY;
