-- ==================== CREATE TBL_GROUP_CHAT_MESSAGES TABLE ====================
-- File: database/sql/tables/create_tbl_group_chat_messages_table.sql
-- Created: 2026-04-03
-- Purpose: Store text messages that belong to subject group chats.

CREATE TABLE IF NOT EXISTS public.tbl_group_chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_chat_id BIGINT NOT NULL REFERENCES public.tbl_group_chats(id) ON DELETE CASCADE,
  sender_user_id BIGINT NOT NULL REFERENCES public.tbl_users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT tbl_group_chat_messages_content_check CHECK (char_length(btrim(content)) > 0)
);

-- Enable RLS
ALTER TABLE public.tbl_group_chat_messages ENABLE ROW LEVEL SECURITY;
