export const quizzes = [
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    name: "Web Development",
    email: "Educator",
    subject: "Quiz #1",
    text: "This assessment covers HTML structure, semantic tags, CSS selectors, and responsive layout basics.\n\nRead each question carefully before submitting your answers. Once you start the quiz, make sure you complete it within the allowed schedule.\n\nGood luck and do your best.",
    date: "2026-10-22T09:00:00",
    educatorName: "Mark Adrianne Salunga",
    assessmentType: "Midterm",
    startDate: "Oct 22, 2026, 9:00 AM",
    endDate: "Oct 22, 2026, 9:00 AM",
    startTime: "9:00 AM",
    endTime: "9:00 AM",
    schedule: "Oct 22, 2026, 9:00 AM",
    attachmentName: "Web Development Midterm Reviewer.pptx",
    attachmentSize: "2.4 MB",
    attachmentLabel: "PowerPoint Study Material",
    read: true,
    labels: ["pending"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "Database Systems",
    email: "Educator",
    subject: "Quiz #2",
    text: "This assessment focuses on relational models, normalization, SQL joins, and indexing fundamentals.\n\nPrepare your notes before starting and review the sample queries discussed in class.",
    date: "2023-10-22T10:30:00",
    educatorName: "Mark Adrianne Salunga",
    assessmentType: "Midterm",
    startDate: "March 5",
    endDate: "March 5",
    startTime: "1:00pm",
    endTime: "3:00pm",
    schedule: "March 5 | 1:00pm - 3:00pm",
    attachmentName: "Database Systems Reviewer.pptx",
    attachmentSize: "1.9 MB",
    attachmentLabel: "PowerPoint Study Material",
    read: true,
    labels: ["finished"],
  },
  {
    id: "3e7c3f6d-bdf5-46ae-8d90-171300f27ae2",
    name: "Programming Logic",
    email: "Educator",
    subject: "Quiz #3",
    text: "Answer the logic and flow-control questions using the problem-solving steps practiced during lab sessions.\n\nPay close attention to loops, conditions, and expected output.",
    date: "2023-04-10T11:45:00",
    educatorName: "Mark Adrianne Salunga",
    assessmentType: "Midterm",
    startDate: "March 7",
    endDate: "March 7",
    startTime: "9:00am",
    endTime: "11:00am",
    schedule: "March 7 | 9:00am - 11:00am",
    attachmentName: "Programming Logic Reviewer.pptx",
    attachmentSize: "2.1 MB",
    attachmentLabel: "PowerPoint Study Material",
    read: false,
    labels: ["pending"],
  },
  {
    id: "61c35085-72d7-42b4-8d62-738f700d4b92",
    name: "Computer Networks",
    email: "Educator",
    subject: "Quiz #1",
    text: "This assessment includes IP addressing, network topologies, and OSI model questions.\n\nReview the lecture examples before opening the assessment.",
    date: "2023-03-25T13:15:00",
    educatorName: "Mark Adrianne Salunga",
    assessmentType: "Midterm",
    startDate: "March 9",
    endDate: "March 9",
    startTime: "10:00am",
    endTime: "12:00pm",
    schedule: "March 9 | 10:00am - 12:00pm",
    attachmentName: "Computer Networks Reviewer.pptx",
    attachmentSize: "3.2 MB",
    attachmentLabel: "PowerPoint Study Material",
    read: false,
    labels: ["pending"],
  },
  {
    id: "8f7b5db9-d935-4e42-8e05-1f1d0a3dfb97",
    name: "Software Engineering",
    email: "Educator",
    subject: "Quiz #4",
    text: "This quiz measures your understanding of SDLC phases, agile practices, and documentation basics.\n\nMake sure you review the project planning materials before taking the assessment.",
    date: "2023-03-10T15:00:00",
    educatorName: "Mark Adrianne Salunga",
    assessmentType: "Midterm",
    startDate: "March 11",
    endDate: "March 11",
    startTime: "2:00pm",
    endTime: "4:00pm",
    schedule: "March 11 | 2:00pm - 4:00pm",
    attachmentName: "Software Engineering Reviewer.pptx",
    attachmentSize: "2.7 MB",
    attachmentLabel: "PowerPoint Study Material",
    read: false,
    labels: ["finished"],
  },
  {
    id: "1f0f2c02-e299-40de-9b1d-86ef9e42126b",
    name: "Information Management",
    email: "Educator",
    subject: "Quiz #2",
    text: "Answer the assessment items about data governance, records management, and information lifecycle concepts.",
    date: "2023-02-15T16:30:00",
    educatorName: "Mark Adrianne Salunga",
    assessmentType: "Midterm",
    startDate: "March 14",
    endDate: "March 14",
    startTime: "8:00am",
    endTime: "10:00am",
    schedule: "March 14 | 8:00am - 10:00am",
    attachmentName: "Information Management Reviewer.pptx",
    attachmentSize: "1.8 MB",
    attachmentLabel: "PowerPoint Study Material",
    read: true,
    labels: ["finished"],
  },
  {
    id: "17c0a96d-4415-42b1-8b4f-764efab57f66",
    name: "Human Computer Interaction",
    email: "Educator",
    subject: "Quiz #1",
    text: "This assessment focuses on usability principles, design heuristics, and interaction patterns covered in class.",
    date: "2023-01-28T17:45:00",
    educatorName: "Mark Adrianne Salunga",
    assessmentType: "Midterm",
    startDate: "March 16",
    endDate: "March 16",
    startTime: "3:00pm",
    endTime: "5:00pm",
    schedule: "March 16 | 3:00pm - 5:00pm",
    attachmentName: "HCI Reviewer.pptx",
    attachmentSize: "2.0 MB",
    attachmentLabel: "PowerPoint Study Material",
    read: false,
    labels: ["pending"],
  },
  {
    id: "2f0130cb-39fc-44c4-bb3c-0a4337edaaab",
    name: "Data Structures",
    email: "Educator",
    subject: "Quiz #3",
    text: "Complete the assessment on arrays, linked lists, stacks, queues, and algorithm tracing.",
    date: "2022-12-20T18:30:00",
    educatorName: "Mark Adrianne Salunga",
    assessmentType: "Midterm",
    startDate: "March 18",
    endDate: "March 18",
    startTime: "9:00am",
    endTime: "11:00am",
    schedule: "March 18 | 9:00am - 11:00am",
    attachmentName: "Data Structures Reviewer.pptx",
    attachmentSize: "2.5 MB",
    attachmentLabel: "PowerPoint Study Material",
    read: true,
    labels: ["finished"],
  },
  {
    id: "de305d54-75b4-431b-adb2-eb6b9e546014",
    name: "Operating Systems",
    email: "Educator",
    subject: "Quiz #2",
    text: "This assessment includes process management, memory allocation, and file system concepts.",
    date: "2022-11-30T19:15:00",
    educatorName: "Mark Adrianne Salunga",
    assessmentType: "Midterm",
    startDate: "March 20",
    endDate: "March 20",
    startTime: "1:00pm",
    endTime: "3:00pm",
    schedule: "March 20 | 1:00pm - 3:00pm",
    attachmentName: "Operating Systems Reviewer.pptx",
    attachmentSize: "2.9 MB",
    attachmentLabel: "PowerPoint Study Material",
    read: true,
    labels: ["finished"],
  },
  {
    id: "7dd90c63-00f6-40f3-bd87-5060a24e8ee7",
    name: "Systems Analysis",
    email: "Educator",
    subject: "Quiz #1",
    text: "Review requirement gathering, process modeling, and feasibility analysis before taking this assessment.",
    date: "2022-11-05T20:30:00",
    educatorName: "Mark Adrianne Salunga",
    assessmentType: "Midterm",
    startDate: "March 22",
    endDate: "March 22",
    startTime: "8:00am",
    endTime: "10:00am",
    schedule: "March 22 | 8:00am - 10:00am",
    attachmentName: "Systems Analysis Reviewer.pptx",
    attachmentSize: "2.2 MB",
    attachmentLabel: "PowerPoint Study Material",
    read: false,
    labels: ["pending"],
  },
  {
    id: "99a88f78-3eb4-4d87-87b7-7b15a49a0a05",
    name: "Web Development",
    email: "Educator",
    subject: "Quiz #2",
    text: "This assessment focuses on form handling, client-side validation, and layout responsiveness.",
    date: "2022-10-22T09:30:00",
    educatorName: "Mark Adrianne Salunga",
    assessmentType: "Midterm",
    startDate: "March 24",
    endDate: "March 24",
    startTime: "10:00am",
    endTime: "12:00pm",
    schedule: "March 24 | 10:00am - 12:00pm",
    attachmentName: "Web Development Forms Reviewer.pptx",
    attachmentSize: "2.3 MB",
    attachmentLabel: "PowerPoint Study Material",
    read: false,
    labels: ["pending"],
  },
  {
    id: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
    name: "Application Development",
    email: "Educator",
    subject: "Quiz #3",
    text: "Prepare for questions on component structure, state handling, and deployment basics.",
    date: "2022-10-10T10:45:00",
    educatorName: "Mark Adrianne Salunga",
    assessmentType: "Midterm",
    startDate: "March 26",
    endDate: "March 26",
    startTime: "1:00pm",
    endTime: "3:00pm",
    schedule: "March 26 | 1:00pm - 3:00pm",
    attachmentName: "Application Development Reviewer.pptx",
    attachmentSize: "2.6 MB",
    attachmentLabel: "PowerPoint Study Material",
    read: true,
    labels: ["finished"],
  },
  {
    id: "c1a0ecb4-2540-49c5-86f8-21e5ce79e4e6",
    name: "Database Systems",
    email: "Educator",
    subject: "Quiz #4",
    text: "This assessment covers transactions, isolation levels, and query optimization techniques.",
    date: "2022-09-20T12:00:00",
    educatorName: "Mark Adrianne Salunga",
    assessmentType: "Midterm",
    startDate: "March 28",
    endDate: "March 28",
    startTime: "9:00am",
    endTime: "11:00am",
    schedule: "March 28 | 9:00am - 11:00am",
    attachmentName: "Database Transactions Reviewer.pptx",
    attachmentSize: "2.8 MB",
    attachmentLabel: "PowerPoint Study Material",
    read: false,
    labels: ["pending"],
  },
  {
    id: "ba54eefd-4097-4949-99f2-2a9ae4d1a836",
    name: "Computer Networks",
    email: "Educator",
    subject: "Quiz #2",
    text: "Expect routing, subnetting, and protocol questions based on the previous two lectures.",
    date: "2022-09-10T13:15:00",
    educatorName: "Mark Adrianne Salunga",
    assessmentType: "Midterm",
    startDate: "March 30",
    endDate: "March 30",
    startTime: "8:00am",
    endTime: "10:00am",
    schedule: "March 30 | 8:00am - 10:00am",
    attachmentName: "Networking Protocols Reviewer.pptx",
    attachmentSize: "3.0 MB",
    attachmentLabel: "PowerPoint Study Material",
    read: true,
    labels: ["finished"],
  },
  {
    id: "df09b6ed-28bd-4e0c-85a9-9320ec5179aa",
    name: "Programming Logic",
    email: "Educator",
    subject: "Quiz #4",
    text: "This assessment focuses on algorithm design, pseudocode, and output tracing.",
    date: "2022-08-25T15:30:00",
    educatorName: "Mark Adrianne Salunga",
    assessmentType: "Midterm",
    startDate: "April 1",
    endDate: "April 1",
    startTime: "1:00pm",
    endTime: "3:00pm",
    schedule: "April 1 | 1:00pm - 3:00pm",
    attachmentName: "Algorithm Design Reviewer.pptx",
    attachmentSize: "2.1 MB",
    attachmentLabel: "PowerPoint Study Material",
    read: false,
    labels: ["pending"],
  },
  {
    id: "d67c1842-7f8b-4b4b-9be1-1b3b1ab4611d",
    name: "Software Engineering",
    email: "Educator",
    subject: "Quiz #5",
    text: "Answer the assessment using the software architecture and testing topics reviewed this week.",
    date: "2022-08-10T16:45:00",
    educatorName: "Mark Adrianne Salunga",
    assessmentType: "Midterm",
    startDate: "April 3",
    endDate: "April 3",
    startTime: "2:00pm",
    endTime: "4:00pm",
    schedule: "April 3 | 2:00pm - 4:00pm",
    attachmentName: "Software Testing Reviewer.pptx",
    attachmentSize: "2.4 MB",
    attachmentLabel: "PowerPoint Study Material",
    read: true,
    labels: ["finished"],
  },
  {
    id: "6c9a7f94-8329-4d70-95d3-51f68c186ae1",
    name: "Information Management",
    email: "Educator",
    subject: "Quiz #3",
    text: "This assessment measures your understanding of classification, metadata, and information retrieval.",
    date: "2022-07-28T17:30:00",
    educatorName: "Mark Adrianne Salunga",
    assessmentType: "Midterm",
    startDate: "April 5",
    endDate: "April 5",
    startTime: "9:00am",
    endTime: "11:00am",
    schedule: "April 5 | 9:00am - 11:00am",
    attachmentName: "Information Retrieval Reviewer.pptx",
    attachmentSize: "1.7 MB",
    attachmentLabel: "PowerPoint Study Material",
    read: false,
    labels: ["pending"],
  },
]

export type Quiz = (typeof quizzes)[number]

export const accounts = [
  {
    label: "Alicia Koch",
    email: "alicia@example.com",
    icon: (
      <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <title>Gmail</title>
        <path
          d="M24 5.457v13.909c0 .904-.732 1.636-1.636 1.636h-3.819V11.73L12 16.64l-6.545-4.91v9.273H1.636A1.636 1.636 0 0 1 0 19.366V5.457c0-2.023 2.309-3.178 3.927-1.964L5.455 4.64 12 9.548l6.545-4.91 1.528-1.145C21.69 2.28 24 3.434 24 5.457z"
          fill="currentColor"
        />
      </svg>
    ),
  },
  {
    label: "Alicia Koch",
    email: "alicia2@example.com",
    icon: (
      <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <title>Vercel</title>
        <path d="M24 22.525H0l12-21.05 12 21.05z" fill="currentColor" />
      </svg>
    ),
  },
  {
    label: "Alicia Koch",
    email: "alicia3@example.com",
    icon: (
      <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <title>iCloud</title>
        <path
          d="M13.762 4.29a6.51 6.51 0 0 0-5.669 3.332 3.571 3.571 0 0 0-1.558-.36 3.571 3.571 0 0 0-3.516 3A4.918 4.918 0 0 0 0 14.796a4.918 4.918 0 0 0 4.92 4.914 4.93 4.93 0 0 0 .617-.045h14.42c2.305-.272 4.041-2.258 4.043-4.589v-.009a4.594 4.594 0 0 0-3.727-4.508 6.51 6.51 0 0 0-6.511-6.27z"
          fill="currentColor"
        />
      </svg>
    ),
  },
]

export type Account = (typeof accounts)[number]

export const contacts = [
  {
    name: "Emma Johnson",
    email: "emma.johnson@example.com",
  },
  {
    name: "Liam Wilson",
    email: "liam.wilson@example.com",
  },
  {
    name: "Olivia Davis",
    email: "olivia.davis@example.com",
  },
  {
    name: "Noah Martinez",
    email: "noah.martinez@example.com",
  },
  {
    name: "Ava Taylor",
    email: "ava.taylor@example.com",
  },
  {
    name: "Lucas Brown",
    email: "lucas.brown@example.com",
  },
  {
    name: "Sophia Smith",
    email: "sophia.smith@example.com",
  },
  {
    name: "Ethan Wilson",
    email: "ethan.wilson@example.com",
  },
  {
    name: "Isabella Jackson",
    email: "isabella.jackson@example.com",
  },
  {
    name: "Mia Clark",
    email: "mia.clark@example.com",
  },
  {
    name: "Mason Lee",
    email: "mason.lee@example.com",
  },
  {
    name: "Layla Harris",
    email: "layla.harris@example.com",
  },
  {
    name: "William Anderson",
    email: "william.anderson@example.com",
  },
  {
    name: "Ella White",
    email: "ella.white@example.com",
  },
  {
    name: "James Thomas",
    email: "james.thomas@example.com",
  },
  {
    name: "Harper Lewis",
    email: "harper.lewis@example.com",
  },
  {
    name: "Benjamin Moore",
    email: "benjamin.moore@example.com",
  },
  {
    name: "Aria Hall",
    email: "aria.hall@example.com",
  },
  {
    name: "Henry Turner",
    email: "henry.turner@example.com",
  },
  {
    name: "Scarlett Adams",
    email: "scarlett.adams@example.com",
  },
]

export type Contact = (typeof contacts)[number]
