-- ==================== UPDATE ACADEMIC YEAR TABLE STRUCTURE ====================
ALTER TABLE public.academic_year
ADD COLUMN IF NOT EXISTS year TEXT;

-- ==================== COPY CURRENT ACADEMIC YEAR ID INTO YEAR COLUMN ====================
UPDATE public.academic_year
SET year = id::TEXT
WHERE year IS NULL;

-- ==================== ADD UNIQUE CONSTRAINT TO ACADEMIC YEAR YEAR ====================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'academic_year_year_key'
  ) THEN
    ALTER TABLE public.academic_year
    ADD CONSTRAINT academic_year_year_key UNIQUE (year);
  END IF;
END $$;

-- ==================== CREATE NEW ACADEMIC YEAR TABLE WITH IDENTITY ID ====================
CREATE TABLE IF NOT EXISTS public.academic_year_new (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year TEXT NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- ==================== COPY ACADEMIC YEAR DATA TO NEW TABLE ====================
INSERT INTO public.academic_year_new (year, is_active)
SELECT year, is_active
FROM public.academic_year
ON CONFLICT (year) DO NOTHING;

-- ==================== CREATE NEW ACADEMIC TERM TABLE WITH BIGINT FOREIGN KEY ====================
CREATE TABLE IF NOT EXISTS public.academic_term_new (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term_name TEXT NOT NULL,
  semester TEXT NOT NULL CHECK (semester IN ('1st Semester', '2nd Semester')),
  academic_year_id BIGINT NOT NULL REFERENCES public.academic_year_new(id) ON DELETE RESTRICT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT academic_term_new_unique_term UNIQUE (term_name, semester, academic_year_id)
);

-- ==================== COPY ACADEMIC TERM DATA TO NEW TABLE ====================
INSERT INTO public.academic_term_new (term_name, semester, academic_year_id, is_active)
SELECT
  term.term_name,
  term.semester,
  year_map.id,
  term.is_active
FROM public.academic_term AS term
INNER JOIN public.academic_year AS old_year
  ON old_year.id::TEXT = term.academic_year_id::TEXT
INNER JOIN public.academic_year_new AS year_map
  ON year_map.year = old_year.year
ON CONFLICT (term_name, semester, academic_year_id) DO NOTHING;

-- ==================== DISABLE RLS ON NEW TABLES ====================
ALTER TABLE public.academic_year_new DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.academic_term_new DISABLE ROW LEVEL SECURITY;

-- ==================== RENAME OLD TABLES AND PROMOTE NEW TABLES ====================
ALTER TABLE public.academic_term RENAME TO academic_term_old;
ALTER TABLE public.academic_year RENAME TO academic_year_old;
ALTER TABLE public.academic_year_new RENAME TO academic_year;
ALTER TABLE public.academic_term_new RENAME TO academic_term;
