-- ==================== CREATE ACADEMIC YEAR TABLE ====================
CREATE TABLE IF NOT EXISTS public.academic_year (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year TEXT NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- RLS is disabled for now because auth and roles are not yet ready
ALTER TABLE public.academic_year DISABLE ROW LEVEL SECURITY;

-- ==================== CREATE ACADEMIC TERM TABLE ====================
CREATE TABLE IF NOT EXISTS public.academic_term (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term_name TEXT NOT NULL,
  semester TEXT NOT NULL CHECK (semester IN ('1st Semester', '2nd Semester')),
  academic_year_id BIGINT NOT NULL REFERENCES public.academic_year(id) ON DELETE RESTRICT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT academic_term_unique_term UNIQUE (term_name, semester, academic_year_id)
);

-- RLS is disabled for now because auth and roles are not yet ready
ALTER TABLE public.academic_term DISABLE ROW LEVEL SECURITY;
