-- ==================== CREATE ROLES TABLE ====================
CREATE TABLE IF NOT EXISTS public.roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE CHECK (name ~ '^[a-z]+(_[a-z]+)*$'),
  description TEXT NOT NULL,
  is_system BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- ==================== CREATE PERMISSIONS TABLE ====================
CREATE TABLE IF NOT EXISTS public.permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  resource TEXT NOT NULL,
  action TEXT NOT NULL,
  description TEXT NOT NULL,
  module TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  permission_string TEXT GENERATED ALWAYS AS (resource || ':' || action) STORED,
  CONSTRAINT permissions_permission_string_key UNIQUE (permission_string)
);

-- ==================== CREATE ROLE PERMISSIONS TABLE ====================
CREATE TABLE IF NOT EXISTS public.role_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id BIGINT NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
  permission_id BIGINT NOT NULL REFERENCES public.permissions(id) ON DELETE CASCADE,
  CONSTRAINT role_permissions_unique_pair UNIQUE (role_id, permission_id)
);
